-- 证件类型修改
update BI_OTHERACCOUNT 
set CTPY_IC_TYPE = '@N'
WHERE CTPY_IC_TYPE = '@E'

update BI_OTHERACCOUNT 
set CTPY_IC_TYPE = '@N'
WHERE CTPY_IC_TYPE = '@I'

update BI_OTHERACCOUNT 
set CTPY_IC_TYPE = '110001'
WHERE CTPY_IC_TYPE = '11'

update BI_OTHERACCOUNT 
set CTPY_IC_TYPE = '110007'
WHERE CTPY_IC_TYPE = '12'

update BI_OTHERACCOUNT 
set CTPY_IC_TYPE = '110019' 
WHERE CTPY_IC_TYPE = '13'

update BI_OTHERACCOUNT 
set CTPY_IC_TYPE = '110027'
WHERE CTPY_IC_TYPE = '14'

update BI_OTHERACCOUNT 
set CTPY_IC_TYPE = '119999'
WHERE CTPY_IC_TYPE = '19'

update BI_OTHERACCOUNT 
set CTPY_IC_TYPE = '610001'
WHERE CTPY_IC_TYPE = '21'

update BI_OTHERACCOUNT 
set CTPY_IC_TYPE = '619999'
WHERE CTPY_IC_TYPE = '29'