package com.aif.rpt.bas.client;

import java.util.ArrayList;
import java.util.List;

import com.allinfinance.yak.uface.core.client.config.BaseConfig;
import com.allinfinance.yak.uface.core.client.config.PageViewConfig;
import com.allinfinance.yak.uface.core.shared.annotations.reflection.ClassForNameAble;
import com.allinfinance.yak.uface.data.client.command.DatasetCommand;
import com.allinfinance.yak.uface.data.client.dataset.ViewDataset;
import com.allinfinance.yak.uface.ui.component.client.basic.UButton;
import com.allinfinance.yak.uface.ui.component.client.form.UDynamicForm;
import com.allinfinance.yak.uface.ui.component.client.form.fields.USectionItem;
import com.allinfinance.yak.uface.ui.component.client.form.fields.UDateItem;
import com.allinfinance.yak.uface.ui.component.client.form.fields.UMoneyItem;
import com.allinfinance.yak.uface.ui.component.client.form.fields.USelectItem;
import com.allinfinance.yak.uface.ui.component.client.form.fields.UTextAreaItem;
import com.allinfinance.yak.uface.ui.component.client.form.fields.UTextItem;
import com.allinfinance.yak.uface.ui.component.client.form.fields.UCheckboxItem;
import com.allinfinance.yak.uface.ui.component.client.form.fields.UPasswordItem;
import com.allinfinance.yak.uface.ui.component.client.grid.UTable;
import com.allinfinance.yak.uface.ui.component.client.basic.UWindow;
import com.allinfinance.yak.uface.ui.component.client.tabset.UTabset;
import com.allinfinance.yak.uface.ui.component.client.tree.UTreeGrid;
import com.allinfinance.yak.uface.ui.component.client.label.ULabel;
import com.allinfinance.yak.uface.ui.component.client.calendar.UCalendar;
import com.allinfinance.yak.uface.ui.component.client.upload.UBaseUploader;
import com.allinfinance.yak.uface.ui.component.client.view.CommonPageView;

@ClassForNameAble
public class OtherAccount extends CommonPageView {

	protected ViewDataset dsQuery;
	protected ViewDataset dsResult;
	protected ViewDataset dsCountryQuery;
	protected ViewDataset dsCountryResult;
	protected DatasetCommand queryCmd;
	protected DatasetCommand saveCmd;
	protected DatasetCommand qryCountryCmd;
	protected UDynamicForm queryForm;
	protected UTextItem editorCTPY_ACCT_ID;
	protected UTextItem editorCTPY_NAME;
	protected UButton btnQuery;
	protected UTable tableResult;
	protected UButton btnAdd;
	protected UButton btnMod;
	protected UButton btnDel;
	protected UButton btnSave;
	protected UButton btnCancel;
	protected UDynamicForm formAction;
	protected UTextItem editCTPY_ACCT_ID;
	protected USelectItem editCTPY_ACCT_TYPE;
	protected USelectItem editCTPY_IC_TYPE;
	protected UTextItem editCTPY_IC_TYPE_MEMO;
	protected UTextItem editCTPY_IC_CODE;
	protected UTextItem editCTPY_NATIONALITY;
	protected USelectItem editCTPY_TYPE;
	protected UTextItem editCTPY_NAME;
	protected UWindow countryWindow;
	protected UDynamicForm countryQueryForm;
	protected UTextItem countryCode;
	protected UTextItem countryName;
	protected UButton btnCountryQuery;
	protected UButton btnCountryOk;
	protected UButton btnCountryBack;
	protected UTable tableCountryResult;

	@Override
	protected void afterInitDatasets() {
		super.afterInitDatasets();
	}

	@Override
	protected PageViewConfig initConfig() {
		PageViewConfig config = super.initConfig();
		BaseConfig render = config.getRenderConfig();
		super.afterInitControls();

		//datasets init begin
		BaseConfig dataset = config.getDatasetsConfig();

		//dataset dsQuery
		dataset.put("dsQuery", sub_ds_dsQuery());

		//dataset dsResult
		dataset.put("dsResult", sub_ds_dsResult());

		//dataset dsCountryQuery
		dataset.put("dsCountryQuery", sub_ds_dsCountryQuery());

		//dataset dsCountryResult
		dataset.put("dsCountryResult", sub_ds_dsCountryResult());
		//datasets init end

		//commands init begin
		BaseConfig command = config.getCommandsConfig();

		//command queryCmd
		command.put("queryCmd", sub_cmd_queryCmd());

		//command saveCmd
		command.put("saveCmd", sub_cmd_saveCmd());

		//command qryCountryCmd
		command.put("qryCountryCmd", sub_cmd_qryCountryCmd());
		//commands init end

		//renders init begin
		BaseConfig outerLayout = sub_control_outerLayout();
		render.put("outerLayout", outerLayout);
		BaseConfig countryWindow = sub_control_countryWindow();
		render.put("countryWindow", countryWindow);

		//renders init end
		return config;
	}

	private BaseConfig sub_ds_dsQuery(){
		BaseConfig dsQuery = new BaseConfig();
		List<BaseConfig> fieldsdsQuery = new ArrayList<BaseConfig>();
		BaseConfig dsQuery_CTPY_ACCT_ID = new BaseConfig();
		dsQuery_CTPY_ACCT_ID.put("name", "CTPY_ACCT_ID");
		dsQuery_CTPY_ACCT_ID.put("type", "Base");
		dsQuery_CTPY_ACCT_ID.put("title","交易对手账号");
		dsQuery_CTPY_ACCT_ID.put("dataType", "string");
		dsQuery_CTPY_ACCT_ID.put("precision", "38");
		dsQuery_CTPY_ACCT_ID.put("scale", "0");
		dsQuery_CTPY_ACCT_ID.put("leverage", "0");
		dsQuery_CTPY_ACCT_ID.put("defaultValue", "");
		dsQuery_CTPY_ACCT_ID.put("format", "");
		dsQuery_CTPY_ACCT_ID.put("moduleid", "");
		dsQuery_CTPY_ACCT_ID.put("bizCode", "");
		dsQuery_CTPY_ACCT_ID.put("isPrimaryKey", "false");
		dsQuery_CTPY_ACCT_ID.put("isForeignKey", "false");
		dsQuery_CTPY_ACCT_ID.put("dropdown", "");
		dsQuery_CTPY_ACCT_ID.put("nullable", "true");
		dsQuery_CTPY_ACCT_ID.put("nullableError", "");
		dsQuery_CTPY_ACCT_ID.put("lengthRange", "");
		dsQuery_CTPY_ACCT_ID.put("lengthRangeError", "");
		dsQuery_CTPY_ACCT_ID.put("readOnly", "false");
		dsQuery_CTPY_ACCT_ID.put("msgAlign", "right");
		dsQuery_CTPY_ACCT_ID.put("charset", "");
		dsQuery_CTPY_ACCT_ID.put("charsetError", "");
		fieldsdsQuery.add(dsQuery_CTPY_ACCT_ID);
		BaseConfig dsQuery_CTPY_NAME = new BaseConfig();
		dsQuery_CTPY_NAME.put("name", "CTPY_NAME");
		dsQuery_CTPY_NAME.put("type", "Base");
		dsQuery_CTPY_NAME.put("title","对手名称");
		dsQuery_CTPY_NAME.put("dataType", "string");
		dsQuery_CTPY_NAME.put("precision", "38");
		dsQuery_CTPY_NAME.put("scale", "0");
		dsQuery_CTPY_NAME.put("leverage", "0");
		dsQuery_CTPY_NAME.put("defaultValue", "");
		dsQuery_CTPY_NAME.put("format", "");
		dsQuery_CTPY_NAME.put("moduleid", "");
		dsQuery_CTPY_NAME.put("bizCode", "");
		dsQuery_CTPY_NAME.put("isPrimaryKey", "false");
		dsQuery_CTPY_NAME.put("isForeignKey", "false");
		dsQuery_CTPY_NAME.put("dropdown", "");
		dsQuery_CTPY_NAME.put("nullable", "true");
		dsQuery_CTPY_NAME.put("nullableError", "");
		dsQuery_CTPY_NAME.put("lengthRange", "");
		dsQuery_CTPY_NAME.put("lengthRangeError", "");
		dsQuery_CTPY_NAME.put("readOnly", "false");
		dsQuery_CTPY_NAME.put("msgAlign", "right");
		dsQuery_CTPY_NAME.put("charset", "");
		dsQuery_CTPY_NAME.put("charsetError", "");
		fieldsdsQuery.add(dsQuery_CTPY_NAME);
		dsQuery.put("fields", fieldsdsQuery);
		return dsQuery;
	}

	private BaseConfig sub_ds_dsResult(){
		BaseConfig dsResult = new BaseConfig();
		List<BaseConfig> fieldsdsResult = new ArrayList<BaseConfig>();
		BaseConfig dsResult_CTPY_ACCT_ID = new BaseConfig();
		dsResult_CTPY_ACCT_ID.put("name", "CTPY_ACCT_ID");
		dsResult_CTPY_ACCT_ID.put("type", "Base");
		dsResult_CTPY_ACCT_ID.put("title","交易对手账号");
		dsResult_CTPY_ACCT_ID.put("dataType", "string");
		dsResult_CTPY_ACCT_ID.put("precision", "38");
		dsResult_CTPY_ACCT_ID.put("scale", "0");
		dsResult_CTPY_ACCT_ID.put("leverage", "0");
		dsResult_CTPY_ACCT_ID.put("defaultValue", "");
		dsResult_CTPY_ACCT_ID.put("format", "");
		dsResult_CTPY_ACCT_ID.put("moduleid", "");
		dsResult_CTPY_ACCT_ID.put("bizCode", "");
		dsResult_CTPY_ACCT_ID.put("isPrimaryKey", "false");
		dsResult_CTPY_ACCT_ID.put("isForeignKey", "false");
		dsResult_CTPY_ACCT_ID.put("dropdown", "");
		dsResult_CTPY_ACCT_ID.put("nullable", "false");
		dsResult_CTPY_ACCT_ID.put("nullableError", "");
		dsResult_CTPY_ACCT_ID.put("lengthRange", "");
		dsResult_CTPY_ACCT_ID.put("lengthRangeError", "");
		dsResult_CTPY_ACCT_ID.put("readOnly", "false");
		dsResult_CTPY_ACCT_ID.put("msgAlign", "right");
		dsResult_CTPY_ACCT_ID.put("charset", "");
		dsResult_CTPY_ACCT_ID.put("charsetError", "");
		fieldsdsResult.add(dsResult_CTPY_ACCT_ID);
		BaseConfig dsResult_CTPY_ACCT_TYPE = new BaseConfig();
		dsResult_CTPY_ACCT_TYPE.put("name", "CTPY_ACCT_TYPE");
		dsResult_CTPY_ACCT_TYPE.put("type", "Base");
		dsResult_CTPY_ACCT_TYPE.put("title","对手账号类型");
		dsResult_CTPY_ACCT_TYPE.put("dataType", "string");
		dsResult_CTPY_ACCT_TYPE.put("precision", "38");
		dsResult_CTPY_ACCT_TYPE.put("scale", "0");
		dsResult_CTPY_ACCT_TYPE.put("leverage", "0");
		dsResult_CTPY_ACCT_TYPE.put("defaultValue", "");
		dsResult_CTPY_ACCT_TYPE.put("format", "");
		dsResult_CTPY_ACCT_TYPE.put("moduleid", "RPT1307");
		dsResult_CTPY_ACCT_TYPE.put("bizCode", "0000");
		dsResult_CTPY_ACCT_TYPE.put("isPrimaryKey", "false");
		dsResult_CTPY_ACCT_TYPE.put("isForeignKey", "false");
		dsResult_CTPY_ACCT_TYPE.put("dropdown", "");
		dsResult_CTPY_ACCT_TYPE.put("nullable", "false");
		dsResult_CTPY_ACCT_TYPE.put("nullableError", "");
		dsResult_CTPY_ACCT_TYPE.put("lengthRange", "");
		dsResult_CTPY_ACCT_TYPE.put("lengthRangeError", "");
		dsResult_CTPY_ACCT_TYPE.put("readOnly", "false");
		dsResult_CTPY_ACCT_TYPE.put("msgAlign", "right");
		dsResult_CTPY_ACCT_TYPE.put("charset", "");
		dsResult_CTPY_ACCT_TYPE.put("charsetError", "");
		fieldsdsResult.add(dsResult_CTPY_ACCT_TYPE);
		BaseConfig dsResult_CTPY_IC_TYPE = new BaseConfig();
		dsResult_CTPY_IC_TYPE.put("name", "CTPY_IC_TYPE");
		dsResult_CTPY_IC_TYPE.put("type", "Base");
		dsResult_CTPY_IC_TYPE.put("title","对手证件类型");
		dsResult_CTPY_IC_TYPE.put("dataType", "string");
		dsResult_CTPY_IC_TYPE.put("precision", "38");
		dsResult_CTPY_IC_TYPE.put("scale", "0");
		dsResult_CTPY_IC_TYPE.put("leverage", "0");
		dsResult_CTPY_IC_TYPE.put("defaultValue", "");
		dsResult_CTPY_IC_TYPE.put("format", "");
		dsResult_CTPY_IC_TYPE.put("moduleid", "");
		dsResult_CTPY_IC_TYPE.put("bizCode", "");
		dsResult_CTPY_IC_TYPE.put("isPrimaryKey", "false");
		dsResult_CTPY_IC_TYPE.put("isForeignKey", "false");
		dsResult_CTPY_IC_TYPE.put("dropdown", "");
		dsResult_CTPY_IC_TYPE.put("nullable", "false");
		dsResult_CTPY_IC_TYPE.put("nullableError", "");
		dsResult_CTPY_IC_TYPE.put("lengthRange", "");
		dsResult_CTPY_IC_TYPE.put("lengthRangeError", "");
		dsResult_CTPY_IC_TYPE.put("readOnly", "false");
		dsResult_CTPY_IC_TYPE.put("msgAlign", "right");
		dsResult_CTPY_IC_TYPE.put("charset", "");
		dsResult_CTPY_IC_TYPE.put("charsetError", "");
		fieldsdsResult.add(dsResult_CTPY_IC_TYPE);
		BaseConfig dsResult_CTPY_IC_TYPE_MEMO = new BaseConfig();
		dsResult_CTPY_IC_TYPE_MEMO.put("name", "CTPY_IC_TYPE_MEMO");
		dsResult_CTPY_IC_TYPE_MEMO.put("type", "Base");
		dsResult_CTPY_IC_TYPE_MEMO.put("title","对手证件类型备注");
		dsResult_CTPY_IC_TYPE_MEMO.put("dataType", "string");
		dsResult_CTPY_IC_TYPE_MEMO.put("precision", "38");
		dsResult_CTPY_IC_TYPE_MEMO.put("scale", "0");
		dsResult_CTPY_IC_TYPE_MEMO.put("leverage", "0");
		dsResult_CTPY_IC_TYPE_MEMO.put("defaultValue", "");
		dsResult_CTPY_IC_TYPE_MEMO.put("format", "");
		dsResult_CTPY_IC_TYPE_MEMO.put("moduleid", "RPT1302");
		dsResult_CTPY_IC_TYPE_MEMO.put("bizCode", "0000");
		dsResult_CTPY_IC_TYPE_MEMO.put("isPrimaryKey", "false");
		dsResult_CTPY_IC_TYPE_MEMO.put("isForeignKey", "false");
		dsResult_CTPY_IC_TYPE_MEMO.put("dropdown", "");
		dsResult_CTPY_IC_TYPE_MEMO.put("nullable", "true");
		dsResult_CTPY_IC_TYPE_MEMO.put("nullableError", "");
		dsResult_CTPY_IC_TYPE_MEMO.put("lengthRange", "");
		dsResult_CTPY_IC_TYPE_MEMO.put("lengthRangeError", "");
		dsResult_CTPY_IC_TYPE_MEMO.put("readOnly", "false");
		dsResult_CTPY_IC_TYPE_MEMO.put("msgAlign", "right");
		dsResult_CTPY_IC_TYPE_MEMO.put("charset", "");
		dsResult_CTPY_IC_TYPE_MEMO.put("charsetError", "");
		fieldsdsResult.add(dsResult_CTPY_IC_TYPE_MEMO);
		BaseConfig dsResult_CTPY_IC_CODE = new BaseConfig();
		dsResult_CTPY_IC_CODE.put("name", "CTPY_IC_CODE");
		dsResult_CTPY_IC_CODE.put("type", "Base");
		dsResult_CTPY_IC_CODE.put("title","对手证件号码");
		dsResult_CTPY_IC_CODE.put("dataType", "string");
		dsResult_CTPY_IC_CODE.put("precision", "38");
		dsResult_CTPY_IC_CODE.put("scale", "0");
		dsResult_CTPY_IC_CODE.put("leverage", "0");
		dsResult_CTPY_IC_CODE.put("defaultValue", "");
		dsResult_CTPY_IC_CODE.put("format", "");
		dsResult_CTPY_IC_CODE.put("moduleid", "");
		dsResult_CTPY_IC_CODE.put("bizCode", "");
		dsResult_CTPY_IC_CODE.put("isPrimaryKey", "false");
		dsResult_CTPY_IC_CODE.put("isForeignKey", "false");
		dsResult_CTPY_IC_CODE.put("dropdown", "");
		dsResult_CTPY_IC_CODE.put("nullable", "false");
		dsResult_CTPY_IC_CODE.put("nullableError", "");
		dsResult_CTPY_IC_CODE.put("lengthRange", "");
		dsResult_CTPY_IC_CODE.put("lengthRangeError", "");
		dsResult_CTPY_IC_CODE.put("readOnly", "false");
		dsResult_CTPY_IC_CODE.put("msgAlign", "right");
		dsResult_CTPY_IC_CODE.put("charset", "");
		dsResult_CTPY_IC_CODE.put("charsetError", "");
		fieldsdsResult.add(dsResult_CTPY_IC_CODE);
		BaseConfig dsResult_CTPY_NATIONALITY = new BaseConfig();
		dsResult_CTPY_NATIONALITY.put("name", "CTPY_NATIONALITY");
		dsResult_CTPY_NATIONALITY.put("type", "Base");
		dsResult_CTPY_NATIONALITY.put("title","对手国籍");
		dsResult_CTPY_NATIONALITY.put("dataType", "string");
		dsResult_CTPY_NATIONALITY.put("precision", "38");
		dsResult_CTPY_NATIONALITY.put("scale", "0");
		dsResult_CTPY_NATIONALITY.put("leverage", "0");
		dsResult_CTPY_NATIONALITY.put("defaultValue", "");
		dsResult_CTPY_NATIONALITY.put("format", "");
		dsResult_CTPY_NATIONALITY.put("moduleid", "");
		dsResult_CTPY_NATIONALITY.put("bizCode", "");
		dsResult_CTPY_NATIONALITY.put("isPrimaryKey", "false");
		dsResult_CTPY_NATIONALITY.put("isForeignKey", "false");
		dsResult_CTPY_NATIONALITY.put("dropdown", "");
		dsResult_CTPY_NATIONALITY.put("nullable", "false");
		dsResult_CTPY_NATIONALITY.put("nullableError", "");
		dsResult_CTPY_NATIONALITY.put("lengthRange", "");
		dsResult_CTPY_NATIONALITY.put("lengthRangeError", "");
		dsResult_CTPY_NATIONALITY.put("readOnly", "false");
		dsResult_CTPY_NATIONALITY.put("msgAlign", "right");
		dsResult_CTPY_NATIONALITY.put("charset", "");
		dsResult_CTPY_NATIONALITY.put("charsetError", "");
		fieldsdsResult.add(dsResult_CTPY_NATIONALITY);
		BaseConfig dsResult_CTPY_TYPE = new BaseConfig();
		dsResult_CTPY_TYPE.put("name", "CTPY_TYPE");
		dsResult_CTPY_TYPE.put("type", "Base");
		dsResult_CTPY_TYPE.put("title","对手类型");
		dsResult_CTPY_TYPE.put("dataType", "string");
		dsResult_CTPY_TYPE.put("precision", "38");
		dsResult_CTPY_TYPE.put("scale", "0");
		dsResult_CTPY_TYPE.put("leverage", "0");
		dsResult_CTPY_TYPE.put("defaultValue", "");
		dsResult_CTPY_TYPE.put("format", "");
		dsResult_CTPY_TYPE.put("moduleid", "RPT1301");
		dsResult_CTPY_TYPE.put("bizCode", "0000");
		dsResult_CTPY_TYPE.put("isPrimaryKey", "false");
		dsResult_CTPY_TYPE.put("isForeignKey", "false");
		dsResult_CTPY_TYPE.put("dropdown", "");
		dsResult_CTPY_TYPE.put("nullable", "false");
		dsResult_CTPY_TYPE.put("nullableError", "");
		dsResult_CTPY_TYPE.put("lengthRange", "");
		dsResult_CTPY_TYPE.put("lengthRangeError", "");
		dsResult_CTPY_TYPE.put("readOnly", "false");
		dsResult_CTPY_TYPE.put("msgAlign", "right");
		dsResult_CTPY_TYPE.put("charset", "");
		dsResult_CTPY_TYPE.put("charsetError", "");
		fieldsdsResult.add(dsResult_CTPY_TYPE);
		BaseConfig dsResult_CTPY_NAME = new BaseConfig();
		dsResult_CTPY_NAME.put("name", "CTPY_NAME");
		dsResult_CTPY_NAME.put("type", "Base");
		dsResult_CTPY_NAME.put("title","对手名称");
		dsResult_CTPY_NAME.put("dataType", "string");
		dsResult_CTPY_NAME.put("precision", "38");
		dsResult_CTPY_NAME.put("scale", "0");
		dsResult_CTPY_NAME.put("leverage", "0");
		dsResult_CTPY_NAME.put("defaultValue", "");
		dsResult_CTPY_NAME.put("format", "");
		dsResult_CTPY_NAME.put("moduleid", "");
		dsResult_CTPY_NAME.put("bizCode", "");
		dsResult_CTPY_NAME.put("isPrimaryKey", "false");
		dsResult_CTPY_NAME.put("isForeignKey", "false");
		dsResult_CTPY_NAME.put("dropdown", "");
		dsResult_CTPY_NAME.put("nullable", "false");
		dsResult_CTPY_NAME.put("nullableError", "");
		dsResult_CTPY_NAME.put("lengthRange", "");
		dsResult_CTPY_NAME.put("lengthRangeError", "");
		dsResult_CTPY_NAME.put("readOnly", "false");
		dsResult_CTPY_NAME.put("msgAlign", "right");
		dsResult_CTPY_NAME.put("charset", "");
		dsResult_CTPY_NAME.put("charsetError", "");
		fieldsdsResult.add(dsResult_CTPY_NAME);
		dsResult.put("fields", fieldsdsResult);
		return dsResult;
	}

	private BaseConfig sub_ds_dsCountryQuery(){
		BaseConfig dsCountryQuery = new BaseConfig();
		List<BaseConfig> fieldsdsCountryQuery = new ArrayList<BaseConfig>();
		BaseConfig dsCountryQuery_countryCode = new BaseConfig();
		dsCountryQuery_countryCode.put("name", "countryCode");
		dsCountryQuery_countryCode.put("type", "Base");
		dsCountryQuery_countryCode.put("title","国家地区代码");
		dsCountryQuery_countryCode.put("dataType", "string");
		dsCountryQuery_countryCode.put("precision", "38");
		dsCountryQuery_countryCode.put("scale", "0");
		dsCountryQuery_countryCode.put("leverage", "0");
		dsCountryQuery_countryCode.put("defaultValue", "");
		dsCountryQuery_countryCode.put("format", "");
		dsCountryQuery_countryCode.put("moduleid", "");
		dsCountryQuery_countryCode.put("bizCode", "");
		dsCountryQuery_countryCode.put("isPrimaryKey", "false");
		dsCountryQuery_countryCode.put("isForeignKey", "false");
		dsCountryQuery_countryCode.put("dropdown", "");
		dsCountryQuery_countryCode.put("nullable", "true");
		dsCountryQuery_countryCode.put("nullableError", "");
		dsCountryQuery_countryCode.put("lengthRange", "");
		dsCountryQuery_countryCode.put("lengthRangeError", "");
		dsCountryQuery_countryCode.put("readOnly", "false");
		dsCountryQuery_countryCode.put("msgAlign", "right");
		dsCountryQuery_countryCode.put("charset", "");
		dsCountryQuery_countryCode.put("charsetError", "");
		fieldsdsCountryQuery.add(dsCountryQuery_countryCode);
		BaseConfig dsCountryQuery_countryName = new BaseConfig();
		dsCountryQuery_countryName.put("name", "countryName");
		dsCountryQuery_countryName.put("type", "Base");
		dsCountryQuery_countryName.put("title","国家地区名称");
		dsCountryQuery_countryName.put("dataType", "string");
		dsCountryQuery_countryName.put("precision", "38");
		dsCountryQuery_countryName.put("scale", "0");
		dsCountryQuery_countryName.put("leverage", "0");
		dsCountryQuery_countryName.put("defaultValue", "");
		dsCountryQuery_countryName.put("format", "");
		dsCountryQuery_countryName.put("moduleid", "");
		dsCountryQuery_countryName.put("bizCode", "");
		dsCountryQuery_countryName.put("isPrimaryKey", "false");
		dsCountryQuery_countryName.put("isForeignKey", "false");
		dsCountryQuery_countryName.put("dropdown", "");
		dsCountryQuery_countryName.put("nullable", "true");
		dsCountryQuery_countryName.put("nullableError", "");
		dsCountryQuery_countryName.put("lengthRange", "");
		dsCountryQuery_countryName.put("lengthRangeError", "");
		dsCountryQuery_countryName.put("readOnly", "false");
		dsCountryQuery_countryName.put("msgAlign", "right");
		dsCountryQuery_countryName.put("charset", "");
		dsCountryQuery_countryName.put("charsetError", "");
		fieldsdsCountryQuery.add(dsCountryQuery_countryName);
		dsCountryQuery.put("fields", fieldsdsCountryQuery);
		return dsCountryQuery;
	}

	private BaseConfig sub_ds_dsCountryResult(){
		BaseConfig dsCountryResult = new BaseConfig();
		List<BaseConfig> fieldsdsCountryResult = new ArrayList<BaseConfig>();
		BaseConfig dsCountryResult_countryCode = new BaseConfig();
		dsCountryResult_countryCode.put("name", "countryCode");
		dsCountryResult_countryCode.put("type", "Base");
		dsCountryResult_countryCode.put("title","国家地区代码");
		dsCountryResult_countryCode.put("dataType", "string");
		dsCountryResult_countryCode.put("precision", "38");
		dsCountryResult_countryCode.put("scale", "0");
		dsCountryResult_countryCode.put("leverage", "0");
		dsCountryResult_countryCode.put("defaultValue", "");
		dsCountryResult_countryCode.put("format", "");
		dsCountryResult_countryCode.put("moduleid", "");
		dsCountryResult_countryCode.put("bizCode", "");
		dsCountryResult_countryCode.put("isPrimaryKey", "false");
		dsCountryResult_countryCode.put("isForeignKey", "false");
		dsCountryResult_countryCode.put("dropdown", "");
		dsCountryResult_countryCode.put("nullable", "true");
		dsCountryResult_countryCode.put("nullableError", "");
		dsCountryResult_countryCode.put("lengthRange", "");
		dsCountryResult_countryCode.put("lengthRangeError", "");
		dsCountryResult_countryCode.put("readOnly", "false");
		dsCountryResult_countryCode.put("msgAlign", "right");
		dsCountryResult_countryCode.put("charset", "");
		dsCountryResult_countryCode.put("charsetError", "");
		fieldsdsCountryResult.add(dsCountryResult_countryCode);
		BaseConfig dsCountryResult_countryName = new BaseConfig();
		dsCountryResult_countryName.put("name", "countryName");
		dsCountryResult_countryName.put("type", "Base");
		dsCountryResult_countryName.put("title","国家地区名称");
		dsCountryResult_countryName.put("dataType", "string");
		dsCountryResult_countryName.put("precision", "38");
		dsCountryResult_countryName.put("scale", "0");
		dsCountryResult_countryName.put("leverage", "0");
		dsCountryResult_countryName.put("defaultValue", "");
		dsCountryResult_countryName.put("format", "");
		dsCountryResult_countryName.put("moduleid", "");
		dsCountryResult_countryName.put("bizCode", "");
		dsCountryResult_countryName.put("isPrimaryKey", "false");
		dsCountryResult_countryName.put("isForeignKey", "false");
		dsCountryResult_countryName.put("dropdown", "");
		dsCountryResult_countryName.put("nullable", "true");
		dsCountryResult_countryName.put("nullableError", "");
		dsCountryResult_countryName.put("lengthRange", "");
		dsCountryResult_countryName.put("lengthRangeError", "");
		dsCountryResult_countryName.put("readOnly", "false");
		dsCountryResult_countryName.put("msgAlign", "right");
		dsCountryResult_countryName.put("charset", "");
		dsCountryResult_countryName.put("charsetError", "");
		fieldsdsCountryResult.add(dsCountryResult_countryName);
		dsCountryResult.put("fields", fieldsdsCountryResult);
		return dsCountryResult;
	}

	private BaseConfig sub_cmd_queryCmd(){
		BaseConfig queryCmd = new BaseConfig();
		List<BaseConfig> fieldsqueryCmd = new ArrayList<BaseConfig>();
		BaseConfig queryCmd_queryItem = new BaseConfig();
		queryCmd_queryItem.put("id", "queryItem");
		queryCmd_queryItem.put("type", "Sql");
		queryCmd_queryItem.put("bizType", "Query");
		queryCmd_queryItem.put("ref", "");
		queryCmd_queryItem.put("callbackFields", "");
		queryCmd_queryItem.put("backfillFields", "");
		queryCmd_queryItem.put("flushDataOnSuccess", "false");
		queryCmd_queryItem.put("clearOriginalData", "false");
		queryCmd_queryItem.put("bank", "");
		queryCmd_queryItem.put("application", "");
		queryCmd_queryItem.put("pkgId", "");
		queryCmd_queryItem.put("datascope", "Current");
		queryCmd_queryItem.put("sqlId", "");
		queryCmd_queryItem.put("optType", "selectList");
		queryCmd_queryItem.put("entityDataset", "dsResult");
		queryCmd_queryItem.put("conditionDataset", "dsQuery");
		queryCmd_queryItem.put("validForm", "");
		queryCmd_queryItem.put("templateTable", "tableResult");
		queryCmd_queryItem.put("ifNoneResultNotification", "true");
		fieldsqueryCmd.add(queryCmd_queryItem);
		queryCmd.put("items", fieldsqueryCmd);
		return queryCmd;
	}

	private BaseConfig sub_cmd_saveCmd(){
		BaseConfig saveCmd = new BaseConfig();
		List<BaseConfig> fieldssaveCmd = new ArrayList<BaseConfig>();
		BaseConfig saveCmd_saveItem = new BaseConfig();
		saveCmd_saveItem.put("id", "saveItem");
		saveCmd_saveItem.put("type", "Dataset");
		saveCmd_saveItem.put("bizType", "Commit");
		saveCmd_saveItem.put("ref", "");
		saveCmd_saveItem.put("callbackFields", "");
		saveCmd_saveItem.put("backfillFields", "");
		saveCmd_saveItem.put("flushDataOnSuccess", "false");
		saveCmd_saveItem.put("clearOriginalData", "false");
		saveCmd_saveItem.put("bank", "");
		saveCmd_saveItem.put("application", "");
		saveCmd_saveItem.put("pkgId", "");
		saveCmd_saveItem.put("datascope", "Current");
		saveCmd_saveItem.put("sqlId", "");
		saveCmd_saveItem.put("optType", "selectOne");
		saveCmd_saveItem.put("entityDataset", "dsResult");
		saveCmd_saveItem.put("conditionDataset", "dsResult");
		saveCmd_saveItem.put("validForm", "");
		saveCmd_saveItem.put("templateTable", "tableResult");
		saveCmd_saveItem.put("ifNoneResultNotification", "true");
		fieldssaveCmd.add(saveCmd_saveItem);
		saveCmd.put("items", fieldssaveCmd);
		return saveCmd;
	}

	private BaseConfig sub_cmd_qryCountryCmd(){
		BaseConfig qryCountryCmd = new BaseConfig();
		List<BaseConfig> fieldsqryCountryCmd = new ArrayList<BaseConfig>();
		BaseConfig qryCountryCmd_qryCountryItem = new BaseConfig();
		qryCountryCmd_qryCountryItem.put("id", "qryCountryItem");
		qryCountryCmd_qryCountryItem.put("type", "Dataset");
		qryCountryCmd_qryCountryItem.put("bizType", "Query");
		qryCountryCmd_qryCountryItem.put("ref", "");
		qryCountryCmd_qryCountryItem.put("callbackFields", "");
		qryCountryCmd_qryCountryItem.put("backfillFields", "");
		qryCountryCmd_qryCountryItem.put("flushDataOnSuccess", "false");
		qryCountryCmd_qryCountryItem.put("clearOriginalData", "false");
		qryCountryCmd_qryCountryItem.put("bank", "");
		qryCountryCmd_qryCountryItem.put("application", "");
		qryCountryCmd_qryCountryItem.put("pkgId", "");
		qryCountryCmd_qryCountryItem.put("datascope", "Current");
		qryCountryCmd_qryCountryItem.put("sqlId", "");
		qryCountryCmd_qryCountryItem.put("optType", "selectList");
		qryCountryCmd_qryCountryItem.put("entityDataset", "dsCountryResult");
		qryCountryCmd_qryCountryItem.put("conditionDataset", "dsCountryQuery");
		qryCountryCmd_qryCountryItem.put("validForm", "");
		qryCountryCmd_qryCountryItem.put("templateTable", "");
		qryCountryCmd_qryCountryItem.put("ifNoneResultNotification", "true");
		fieldsqryCountryCmd.add(qryCountryCmd_qryCountryItem);
		qryCountryCmd.put("items", fieldsqryCountryCmd);
		return qryCountryCmd;
	}

	private BaseConfig sub_control_queryForm() {
		BaseConfig queryForm = new BaseConfig();
		queryForm.setXmlTag("Form");
		queryForm.put("id", "queryForm");
		queryForm.put("fragmentId", "对手方账户信息维");
		queryForm.put("type", "Auto");
		queryForm.put("title", "");
		queryForm.put("dataset", "dsQuery");
		queryForm.put("width", "");
		queryForm.put("height", "");
		queryForm.put("enable", "true");
		queryForm.put("readOnly", "false");
		queryForm.put("visible", "true");
		queryForm.put("expandRatio", "");
		queryForm.put("numCols", "4");
		List<BaseConfig> queryFormItemList = new ArrayList<BaseConfig>();
		BaseConfig queryForm_editorCTPY_ACCT_ID = new BaseConfig();
		queryForm_editorCTPY_ACCT_ID.setXmlTag("FormItem");
		queryForm_editorCTPY_ACCT_ID.put("required", "false");
		queryForm_editorCTPY_ACCT_ID.put("requiredMessage", "");
		queryForm_editorCTPY_ACCT_ID.put("id", "editorCTPY_ACCT_ID");
		queryForm_editorCTPY_ACCT_ID.put("fragmentId", "");
		queryForm_editorCTPY_ACCT_ID.put("type", "Text");
		queryForm_editorCTPY_ACCT_ID.put("leftMedian", "");
		queryForm_editorCTPY_ACCT_ID.put("rightMedian", "");
		queryForm_editorCTPY_ACCT_ID.put("title", "交易对手账号");
		queryForm_editorCTPY_ACCT_ID.put("dataset", "dsQuery");
		queryForm_editorCTPY_ACCT_ID.put("name", "CTPY_ACCT_ID");
		queryForm_editorCTPY_ACCT_ID.put("resolution", "");
		queryForm_editorCTPY_ACCT_ID.put("format", "");
		queryForm_editorCTPY_ACCT_ID.put("picker", "");
		queryForm_editorCTPY_ACCT_ID.put("componentAlignment", "Middle_Left");
		queryForm_editorCTPY_ACCT_ID.put("labelAlignment", "Middle_Right");
		queryForm_editorCTPY_ACCT_ID.put("columnStart", "1");
		queryForm_editorCTPY_ACCT_ID.put("columnEnd", "4");
		queryForm_editorCTPY_ACCT_ID.put("rowStart", "1");
		queryForm_editorCTPY_ACCT_ID.put("rowEnd", "1");
		queryForm_editorCTPY_ACCT_ID.put("columns", "");
		queryForm_editorCTPY_ACCT_ID.put("rows", "");
		queryForm_editorCTPY_ACCT_ID.put("colSpan", "");
		queryForm_editorCTPY_ACCT_ID.put("rowSpan", "");
		queryForm_editorCTPY_ACCT_ID.put("width", "100%");
		queryForm_editorCTPY_ACCT_ID.put("height", "");
		queryForm_editorCTPY_ACCT_ID.put("symbol", "");
		queryForm_editorCTPY_ACCT_ID.put("maxLength", "");
		queryForm_editorCTPY_ACCT_ID.put("labelWidth", "");
		queryForm_editorCTPY_ACCT_ID.put("enable", "true");
		queryForm_editorCTPY_ACCT_ID.put("readOnly", "false");
		queryForm_editorCTPY_ACCT_ID.put("visible", "true");
		queryForm_editorCTPY_ACCT_ID.put("dbcshortcut", "");
		queryFormItemList.add(queryForm_editorCTPY_ACCT_ID);
		BaseConfig queryForm_editorCTPY_NAME = new BaseConfig();
		queryForm_editorCTPY_NAME.setXmlTag("FormItem");
		queryForm_editorCTPY_NAME.put("required", "false");
		queryForm_editorCTPY_NAME.put("requiredMessage", "");
		queryForm_editorCTPY_NAME.put("id", "editorCTPY_NAME");
		queryForm_editorCTPY_NAME.put("fragmentId", "");
		queryForm_editorCTPY_NAME.put("type", "Text");
		queryForm_editorCTPY_NAME.put("leftMedian", "");
		queryForm_editorCTPY_NAME.put("rightMedian", "");
		queryForm_editorCTPY_NAME.put("title", "对手名称");
		queryForm_editorCTPY_NAME.put("dataset", "dsQuery");
		queryForm_editorCTPY_NAME.put("name", "CTPY_NAME");
		queryForm_editorCTPY_NAME.put("resolution", "");
		queryForm_editorCTPY_NAME.put("format", "");
		queryForm_editorCTPY_NAME.put("picker", "");
		queryForm_editorCTPY_NAME.put("componentAlignment", "Middle_Left");
		queryForm_editorCTPY_NAME.put("labelAlignment", "Middle_Right");
		queryForm_editorCTPY_NAME.put("columnStart", "5");
		queryForm_editorCTPY_NAME.put("columnEnd", "8");
		queryForm_editorCTPY_NAME.put("rowStart", "1");
		queryForm_editorCTPY_NAME.put("rowEnd", "1");
		queryForm_editorCTPY_NAME.put("columns", "");
		queryForm_editorCTPY_NAME.put("rows", "");
		queryForm_editorCTPY_NAME.put("colSpan", "");
		queryForm_editorCTPY_NAME.put("rowSpan", "");
		queryForm_editorCTPY_NAME.put("width", "100%");
		queryForm_editorCTPY_NAME.put("height", "");
		queryForm_editorCTPY_NAME.put("symbol", "");
		queryForm_editorCTPY_NAME.put("maxLength", "");
		queryForm_editorCTPY_NAME.put("labelWidth", "");
		queryForm_editorCTPY_NAME.put("enable", "true");
		queryForm_editorCTPY_NAME.put("readOnly", "false");
		queryForm_editorCTPY_NAME.put("visible", "true");
		queryForm_editorCTPY_NAME.put("dbcshortcut", "");
		queryFormItemList.add(queryForm_editorCTPY_NAME);
		queryForm.put("formItemList",queryFormItemList);
		return queryForm;
	}

	private BaseConfig sub_control_btnQuery() {
		BaseConfig btnQuery = new BaseConfig();
		btnQuery.setXmlTag("Button");
		btnQuery.put("id", "btnQuery");
		btnQuery.put("fragmentId", "");
		btnQuery.put("type", "Base");
		btnQuery.put("title", "查询");
		btnQuery.put("width", "");
		btnQuery.put("height", "");
		btnQuery.put("componentAlignment", "Middle_Left");
		btnQuery.put("command", "");
		btnQuery.put("callbackCommand", "");
		btnQuery.put("columnStart", "9");
		btnQuery.put("columnEnd", "12");
		btnQuery.put("rowStart", "1");
		btnQuery.put("rowEnd", "1");
		btnQuery.put("enable", "true");
		btnQuery.put("readOnly", "false");
		btnQuery.put("visible", "true");
		btnQuery.put("expandRatio", "");
		btnQuery.put("shortcut", "");
		return btnQuery;
	}

	private BaseConfig sub_control_queryBtnLayout() {
		BaseConfig queryBtnLayout = new BaseConfig();
		queryBtnLayout.setXmlTag("Layout");
		queryBtnLayout.put("id", "queryBtnLayout");
		queryBtnLayout.put("fragmentId", "");
		queryBtnLayout.put("type", "HFlow");
		queryBtnLayout.put("row", "");
		queryBtnLayout.put("column", "");
		queryBtnLayout.put("labelAlign", "left");
		queryBtnLayout.put("componentAlignment", "Top_Left");
		queryBtnLayout.put("margin", "false");
		queryBtnLayout.put("spacing", "false");
		queryBtnLayout.put("columnExpandRatio", "");
		queryBtnLayout.put("width", "");
		queryBtnLayout.put("height", "");
		queryBtnLayout.put("enable", "true");
		queryBtnLayout.put("readOnly", "false");
		queryBtnLayout.put("visible", "true");
		List<BaseConfig> queryBtnLayoutList = new ArrayList<BaseConfig>();
		queryBtnLayout.put("queryBtnLayoutList",queryBtnLayoutList);
		BaseConfig btnQuery = sub_control_btnQuery();
		queryBtnLayoutList.add(btnQuery);
		return queryBtnLayout;
	}

	private BaseConfig sub_control_tableResult() {
		BaseConfig tableResult = new BaseConfig();
		tableResult.setXmlTag("Table");
		tableResult.put("id", "tableResult");
		tableResult.put("fragmentId", "");
		tableResult.put("type", "Base");
		tableResult.put("caption", "");
		tableResult.put("hightLight", "true");
		tableResult.put("dataset", "dsResult");
		tableResult.put("width", "100%");
		tableResult.put("height", "455px");
		tableResult.put("enable", "true");
		tableResult.put("readOnly", "false");
		tableResult.put("visible", "true");
		tableResult.put("selectField", "");
		tableResult.put("reorderingAllowed", "false");
		tableResult.put("collapsingAllowed", "false");
		tableResult.put("expandRatio", "");
		List<BaseConfig> tableResultFieldList = new ArrayList<BaseConfig>();
		BaseConfig CTPY_ACCT_ID = new BaseConfig();
		CTPY_ACCT_ID.setXmlTag("ListGridField");
		CTPY_ACCT_ID.put("type", "Base");
		CTPY_ACCT_ID.put("name", "CTPY_ACCT_ID");
		CTPY_ACCT_ID.put("id", "CTPY_ACCT_ID");
		CTPY_ACCT_ID.put("field", "CTPY_ACCT_ID");
		CTPY_ACCT_ID.put("title", "交易对手账号");
		CTPY_ACCT_ID.put("moduleid", "");
		CTPY_ACCT_ID.put("bizCode", "");
		CTPY_ACCT_ID.put("dropdown", "");
		CTPY_ACCT_ID.put("dateFormat", "");
		CTPY_ACCT_ID.put("moneyFormat", "");
		CTPY_ACCT_ID.put("width", "");
		CTPY_ACCT_ID.put("columnAlignment", "Align_left");
		CTPY_ACCT_ID.put("enable", "true");
		CTPY_ACCT_ID.put("readOnly", "false");
		CTPY_ACCT_ID.put("visible", "true");
		CTPY_ACCT_ID.put("addUp", "false");
		tableResultFieldList.add(CTPY_ACCT_ID);
		BaseConfig CTPY_ACCT_TYPE = new BaseConfig();
		CTPY_ACCT_TYPE.setXmlTag("ListGridField");
		CTPY_ACCT_TYPE.put("type", "Base");
		CTPY_ACCT_TYPE.put("name", "CTPY_ACCT_TYPE");
		CTPY_ACCT_TYPE.put("id", "CTPY_ACCT_TYPE");
		CTPY_ACCT_TYPE.put("field", "CTPY_ACCT_TYPE");
		CTPY_ACCT_TYPE.put("title", "对手账号类型");
		CTPY_ACCT_TYPE.put("moduleid", "RPT1308");
		CTPY_ACCT_TYPE.put("bizCode", "0000");
		CTPY_ACCT_TYPE.put("dropdown", "");
		CTPY_ACCT_TYPE.put("dateFormat", "");
		CTPY_ACCT_TYPE.put("moneyFormat", "");
		CTPY_ACCT_TYPE.put("width", "");
		CTPY_ACCT_TYPE.put("columnAlignment", "Align_left");
		CTPY_ACCT_TYPE.put("enable", "true");
		CTPY_ACCT_TYPE.put("readOnly", "false");
		CTPY_ACCT_TYPE.put("visible", "true");
		CTPY_ACCT_TYPE.put("addUp", "false");
		tableResultFieldList.add(CTPY_ACCT_TYPE);
		BaseConfig CTPY_IC_TYPE = new BaseConfig();
		CTPY_IC_TYPE.setXmlTag("ListGridField");
		CTPY_IC_TYPE.put("type", "Base");
		CTPY_IC_TYPE.put("name", "CTPY_IC_TYPE");
		CTPY_IC_TYPE.put("id", "CTPY_IC_TYPE");
		CTPY_IC_TYPE.put("field", "CTPY_IC_TYPE");
		CTPY_IC_TYPE.put("title", "对手证件类型");
		CTPY_IC_TYPE.put("moduleid", "RPT1302");
		CTPY_IC_TYPE.put("bizCode", "0000");
		CTPY_IC_TYPE.put("dropdown", "");
		CTPY_IC_TYPE.put("dateFormat", "");
		CTPY_IC_TYPE.put("moneyFormat", "");
		CTPY_IC_TYPE.put("width", "");
		CTPY_IC_TYPE.put("columnAlignment", "Align_left");
		CTPY_IC_TYPE.put("enable", "true");
		CTPY_IC_TYPE.put("readOnly", "false");
		CTPY_IC_TYPE.put("visible", "true");
		CTPY_IC_TYPE.put("addUp", "false");
		tableResultFieldList.add(CTPY_IC_TYPE);
		BaseConfig CTPY_IC_TYPE_MEMO = new BaseConfig();
		CTPY_IC_TYPE_MEMO.setXmlTag("ListGridField");
		CTPY_IC_TYPE_MEMO.put("type", "Base");
		CTPY_IC_TYPE_MEMO.put("name", "CTPY_IC_TYPE_MEMO");
		CTPY_IC_TYPE_MEMO.put("id", "CTPY_IC_TYPE_MEMO");
		CTPY_IC_TYPE_MEMO.put("field", "CTPY_IC_TYPE_MEMO");
		CTPY_IC_TYPE_MEMO.put("title", "对手证件类型备注");
		CTPY_IC_TYPE_MEMO.put("moduleid", "");
		CTPY_IC_TYPE_MEMO.put("bizCode", "");
		CTPY_IC_TYPE_MEMO.put("dropdown", "");
		CTPY_IC_TYPE_MEMO.put("dateFormat", "");
		CTPY_IC_TYPE_MEMO.put("moneyFormat", "");
		CTPY_IC_TYPE_MEMO.put("width", "");
		CTPY_IC_TYPE_MEMO.put("columnAlignment", "Align_left");
		CTPY_IC_TYPE_MEMO.put("enable", "true");
		CTPY_IC_TYPE_MEMO.put("readOnly", "false");
		CTPY_IC_TYPE_MEMO.put("visible", "true");
		CTPY_IC_TYPE_MEMO.put("addUp", "false");
		tableResultFieldList.add(CTPY_IC_TYPE_MEMO);
		BaseConfig CTPY_IC_CODE = new BaseConfig();
		CTPY_IC_CODE.setXmlTag("ListGridField");
		CTPY_IC_CODE.put("type", "Base");
		CTPY_IC_CODE.put("name", "CTPY_IC_CODE");
		CTPY_IC_CODE.put("id", "CTPY_IC_CODE");
		CTPY_IC_CODE.put("field", "CTPY_IC_CODE");
		CTPY_IC_CODE.put("title", "对手证件号码");
		CTPY_IC_CODE.put("moduleid", "");
		CTPY_IC_CODE.put("bizCode", "");
		CTPY_IC_CODE.put("dropdown", "");
		CTPY_IC_CODE.put("dateFormat", "");
		CTPY_IC_CODE.put("moneyFormat", "");
		CTPY_IC_CODE.put("width", "");
		CTPY_IC_CODE.put("columnAlignment", "Align_left");
		CTPY_IC_CODE.put("enable", "true");
		CTPY_IC_CODE.put("readOnly", "false");
		CTPY_IC_CODE.put("visible", "true");
		CTPY_IC_CODE.put("addUp", "false");
		tableResultFieldList.add(CTPY_IC_CODE);
		BaseConfig CTPY_NATIONALITY = new BaseConfig();
		CTPY_NATIONALITY.setXmlTag("ListGridField");
		CTPY_NATIONALITY.put("type", "Base");
		CTPY_NATIONALITY.put("name", "CTPY_NATIONALITY");
		CTPY_NATIONALITY.put("id", "CTPY_NATIONALITY");
		CTPY_NATIONALITY.put("field", "CTPY_NATIONALITY");
		CTPY_NATIONALITY.put("title", "对手国籍");
		CTPY_NATIONALITY.put("moduleid", "");
		CTPY_NATIONALITY.put("bizCode", "");
		CTPY_NATIONALITY.put("dropdown", "");
		CTPY_NATIONALITY.put("dateFormat", "");
		CTPY_NATIONALITY.put("moneyFormat", "");
		CTPY_NATIONALITY.put("width", "");
		CTPY_NATIONALITY.put("columnAlignment", "Align_left");
		CTPY_NATIONALITY.put("enable", "true");
		CTPY_NATIONALITY.put("readOnly", "false");
		CTPY_NATIONALITY.put("visible", "true");
		CTPY_NATIONALITY.put("addUp", "false");
		tableResultFieldList.add(CTPY_NATIONALITY);
		BaseConfig CTPY_TYPE = new BaseConfig();
		CTPY_TYPE.setXmlTag("ListGridField");
		CTPY_TYPE.put("type", "Base");
		CTPY_TYPE.put("name", "CTPY_TYPE");
		CTPY_TYPE.put("id", "CTPY_TYPE");
		CTPY_TYPE.put("field", "CTPY_TYPE");
		CTPY_TYPE.put("title", "对手类型");
		CTPY_TYPE.put("moduleid", "RPT1301");
		CTPY_TYPE.put("bizCode", "0000");
		CTPY_TYPE.put("dropdown", "");
		CTPY_TYPE.put("dateFormat", "");
		CTPY_TYPE.put("moneyFormat", "");
		CTPY_TYPE.put("width", "");
		CTPY_TYPE.put("columnAlignment", "Align_left");
		CTPY_TYPE.put("enable", "true");
		CTPY_TYPE.put("readOnly", "false");
		CTPY_TYPE.put("visible", "true");
		CTPY_TYPE.put("addUp", "false");
		tableResultFieldList.add(CTPY_TYPE);
		BaseConfig CTPY_NAME = new BaseConfig();
		CTPY_NAME.setXmlTag("ListGridField");
		CTPY_NAME.put("type", "Base");
		CTPY_NAME.put("name", "CTPY_NAME");
		CTPY_NAME.put("id", "CTPY_NAME");
		CTPY_NAME.put("field", "CTPY_NAME");
		CTPY_NAME.put("title", "对手名称");
		CTPY_NAME.put("moduleid", "");
		CTPY_NAME.put("bizCode", "");
		CTPY_NAME.put("dropdown", "");
		CTPY_NAME.put("dateFormat", "");
		CTPY_NAME.put("moneyFormat", "");
		CTPY_NAME.put("width", "");
		CTPY_NAME.put("columnAlignment", "Align_left");
		CTPY_NAME.put("enable", "true");
		CTPY_NAME.put("readOnly", "false");
		CTPY_NAME.put("visible", "true");
		CTPY_NAME.put("addUp", "false");
		tableResultFieldList.add(CTPY_NAME);
		tableResult.put("tableFieldConfigList",tableResultFieldList);
		return tableResult;
	}

	private BaseConfig sub_control_paging() {
		BaseConfig paging = new BaseConfig();
		paging.setXmlTag("Navigation");
		paging.put("id", "paging");
		paging.put("fragmentId", "");
		paging.put("type", "Pagebar");
		paging.put("dataset", "dsResult");
		paging.put("showPagesize", "false");
		paging.put("showFirstAndLast", "true");
		paging.put("showRefresh", "true");
		paging.put("showDetail", "true");
		paging.put("showTotalCount", "true");
		paging.put("enable", "true");
		paging.put("readOnly", "false");
		paging.put("visible", "true");
		return paging;
	}

	private BaseConfig sub_control_paginglayout() {
		BaseConfig paginglayout = new BaseConfig();
		paginglayout.setXmlTag("Layout");
		paginglayout.put("id", "paginglayout");
		paginglayout.put("fragmentId", "");
		paginglayout.put("type", "HFlow");
		paginglayout.put("row", "");
		paginglayout.put("column", "");
		paginglayout.put("labelAlign", "left");
		paginglayout.put("componentAlignment", "Middle_Right");
		paginglayout.put("margin", "false");
		paginglayout.put("spacing", "false");
		paginglayout.put("columnExpandRatio", "");
		paginglayout.put("width", "100%");
		paginglayout.put("height", "");
		paginglayout.put("enable", "true");
		paginglayout.put("readOnly", "false");
		paginglayout.put("visible", "true");
		List<BaseConfig> paginglayoutList = new ArrayList<BaseConfig>();
		paginglayout.put("paginglayoutList",paginglayoutList);
		BaseConfig paging = sub_control_paging();
		paginglayoutList.add(paging);
		return paginglayout;
	}

	private BaseConfig sub_control_btnAdd() {
		BaseConfig btnAdd = new BaseConfig();
		btnAdd.setXmlTag("Button");
		btnAdd.put("id", "btnAdd");
		btnAdd.put("fragmentId", "");
		btnAdd.put("type", "Base");
		btnAdd.put("title", "新增");
		btnAdd.put("width", "");
		btnAdd.put("height", "");
		btnAdd.put("componentAlignment", "");
		btnAdd.put("command", "");
		btnAdd.put("callbackCommand", "");
		btnAdd.put("columnStart", "");
		btnAdd.put("columnEnd", "");
		btnAdd.put("rowStart", "");
		btnAdd.put("rowEnd", "");
		btnAdd.put("enable", "true");
		btnAdd.put("readOnly", "false");
		btnAdd.put("visible", "true");
		btnAdd.put("expandRatio", "");
		btnAdd.put("shortcut", "");
		return btnAdd;
	}

	private BaseConfig sub_control_btnMod() {
		BaseConfig btnMod = new BaseConfig();
		btnMod.setXmlTag("Button");
		btnMod.put("id", "btnMod");
		btnMod.put("fragmentId", "");
		btnMod.put("type", "Base");
		btnMod.put("title", "修改");
		btnMod.put("width", "");
		btnMod.put("height", "");
		btnMod.put("componentAlignment", "");
		btnMod.put("command", "");
		btnMod.put("callbackCommand", "");
		btnMod.put("columnStart", "");
		btnMod.put("columnEnd", "");
		btnMod.put("rowStart", "");
		btnMod.put("rowEnd", "");
		btnMod.put("enable", "true");
		btnMod.put("readOnly", "false");
		btnMod.put("visible", "true");
		btnMod.put("expandRatio", "");
		btnMod.put("shortcut", "");
		return btnMod;
	}

	private BaseConfig sub_control_btnDel() {
		BaseConfig btnDel = new BaseConfig();
		btnDel.setXmlTag("Button");
		btnDel.put("id", "btnDel");
		btnDel.put("fragmentId", "");
		btnDel.put("type", "Base");
		btnDel.put("title", "删除");
		btnDel.put("width", "");
		btnDel.put("height", "");
		btnDel.put("componentAlignment", "");
		btnDel.put("command", "");
		btnDel.put("callbackCommand", "");
		btnDel.put("columnStart", "");
		btnDel.put("columnEnd", "");
		btnDel.put("rowStart", "");
		btnDel.put("rowEnd", "");
		btnDel.put("enable", "true");
		btnDel.put("readOnly", "false");
		btnDel.put("visible", "true");
		btnDel.put("expandRatio", "");
		btnDel.put("shortcut", "");
		return btnDel;
	}

	private BaseConfig sub_control_btnSave() {
		BaseConfig btnSave = new BaseConfig();
		btnSave.setXmlTag("Button");
		btnSave.put("id", "btnSave");
		btnSave.put("fragmentId", "");
		btnSave.put("type", "Base");
		btnSave.put("title", "保存");
		btnSave.put("width", "");
		btnSave.put("height", "");
		btnSave.put("componentAlignment", "");
		btnSave.put("command", "");
		btnSave.put("callbackCommand", "");
		btnSave.put("columnStart", "");
		btnSave.put("columnEnd", "");
		btnSave.put("rowStart", "");
		btnSave.put("rowEnd", "");
		btnSave.put("enable", "false");
		btnSave.put("readOnly", "false");
		btnSave.put("visible", "true");
		btnSave.put("expandRatio", "");
		btnSave.put("shortcut", "");
		return btnSave;
	}

	private BaseConfig sub_control_btnCancel() {
		BaseConfig btnCancel = new BaseConfig();
		btnCancel.setXmlTag("Button");
		btnCancel.put("id", "btnCancel");
		btnCancel.put("fragmentId", "");
		btnCancel.put("type", "Base");
		btnCancel.put("title", "取消");
		btnCancel.put("width", "");
		btnCancel.put("height", "");
		btnCancel.put("componentAlignment", "");
		btnCancel.put("command", "");
		btnCancel.put("callbackCommand", "");
		btnCancel.put("columnStart", "");
		btnCancel.put("columnEnd", "");
		btnCancel.put("rowStart", "");
		btnCancel.put("rowEnd", "");
		btnCancel.put("enable", "false");
		btnCancel.put("readOnly", "false");
		btnCancel.put("visible", "true");
		btnCancel.put("expandRatio", "");
		btnCancel.put("shortcut", "");
		return btnCancel;
	}

	private BaseConfig sub_control_btnLayout() {
		BaseConfig btnLayout = new BaseConfig();
		btnLayout.setXmlTag("Layout");
		btnLayout.put("id", "btnLayout");
		btnLayout.put("fragmentId", "");
		btnLayout.put("type", "HFlow");
		btnLayout.put("row", "");
		btnLayout.put("column", "");
		btnLayout.put("labelAlign", "left");
		btnLayout.put("componentAlignment", "Middle_Left");
		btnLayout.put("margin", "false");
		btnLayout.put("spacing", "false");
		btnLayout.put("columnExpandRatio", "");
		btnLayout.put("width", "");
		btnLayout.put("height", "");
		btnLayout.put("enable", "true");
		btnLayout.put("readOnly", "false");
		btnLayout.put("visible", "true");
		List<BaseConfig> btnLayoutList = new ArrayList<BaseConfig>();
		btnLayout.put("btnLayoutList",btnLayoutList);
		BaseConfig btnAdd = sub_control_btnAdd();
		btnLayoutList.add(btnAdd);
		BaseConfig btnMod = sub_control_btnMod();
		btnLayoutList.add(btnMod);
		BaseConfig btnDel = sub_control_btnDel();
		btnLayoutList.add(btnDel);
		BaseConfig btnSave = sub_control_btnSave();
		btnLayoutList.add(btnSave);
		BaseConfig btnCancel = sub_control_btnCancel();
		btnLayoutList.add(btnCancel);
		return btnLayout;
	}

	private BaseConfig sub_control_formAction() {
		BaseConfig formAction = new BaseConfig();
		formAction.setXmlTag("Form");
		formAction.put("id", "formAction");
		formAction.put("fragmentId", "");
		formAction.put("type", "Auto");
		formAction.put("title", "");
		formAction.put("dataset", "dsResult");
		formAction.put("width", "");
		formAction.put("height", "");
		formAction.put("enable", "true");
		formAction.put("readOnly", "true");
		formAction.put("visible", "true");
		formAction.put("expandRatio", "");
		formAction.put("numCols", "4");
		List<BaseConfig> formActionItemList = new ArrayList<BaseConfig>();
		BaseConfig formAction_editCTPY_ACCT_ID = new BaseConfig();
		formAction_editCTPY_ACCT_ID.setXmlTag("FormItem");
		formAction_editCTPY_ACCT_ID.put("required", "true");
		formAction_editCTPY_ACCT_ID.put("requiredMessage", "");
		formAction_editCTPY_ACCT_ID.put("id", "editCTPY_ACCT_ID");
		formAction_editCTPY_ACCT_ID.put("fragmentId", "");
		formAction_editCTPY_ACCT_ID.put("type", "Text");
		formAction_editCTPY_ACCT_ID.put("leftMedian", "");
		formAction_editCTPY_ACCT_ID.put("rightMedian", "");
		formAction_editCTPY_ACCT_ID.put("title", "交易对手账号");
		formAction_editCTPY_ACCT_ID.put("dataset", "dsResult");
		formAction_editCTPY_ACCT_ID.put("name", "CTPY_ACCT_ID");
		formAction_editCTPY_ACCT_ID.put("resolution", "");
		formAction_editCTPY_ACCT_ID.put("format", "");
		formAction_editCTPY_ACCT_ID.put("picker", "");
		formAction_editCTPY_ACCT_ID.put("componentAlignment", "Middle_Left");
		formAction_editCTPY_ACCT_ID.put("labelAlignment", "Middle_Right");
		formAction_editCTPY_ACCT_ID.put("columnStart", "1");
		formAction_editCTPY_ACCT_ID.put("columnEnd", "4");
		formAction_editCTPY_ACCT_ID.put("rowStart", "1");
		formAction_editCTPY_ACCT_ID.put("rowEnd", "1");
		formAction_editCTPY_ACCT_ID.put("columns", "");
		formAction_editCTPY_ACCT_ID.put("rows", "");
		formAction_editCTPY_ACCT_ID.put("colSpan", "");
		formAction_editCTPY_ACCT_ID.put("rowSpan", "");
		formAction_editCTPY_ACCT_ID.put("width", "100%");
		formAction_editCTPY_ACCT_ID.put("height", "");
		formAction_editCTPY_ACCT_ID.put("symbol", "");
		formAction_editCTPY_ACCT_ID.put("maxLength", "");
		formAction_editCTPY_ACCT_ID.put("labelWidth", "");
		formAction_editCTPY_ACCT_ID.put("enable", "true");
		formAction_editCTPY_ACCT_ID.put("readOnly", "true");
		formAction_editCTPY_ACCT_ID.put("visible", "true");
		formAction_editCTPY_ACCT_ID.put("dbcshortcut", "");
		formActionItemList.add(formAction_editCTPY_ACCT_ID);
		BaseConfig formAction_editCTPY_ACCT_TYPE = new BaseConfig();
		formAction_editCTPY_ACCT_TYPE.setXmlTag("FormItem");
		formAction_editCTPY_ACCT_TYPE.put("required", "true");
		formAction_editCTPY_ACCT_TYPE.put("requiredMessage", "");
		formAction_editCTPY_ACCT_TYPE.put("id", "editCTPY_ACCT_TYPE");
		formAction_editCTPY_ACCT_TYPE.put("fragmentId", "");
		formAction_editCTPY_ACCT_TYPE.put("type", "ComboBox");
		formAction_editCTPY_ACCT_TYPE.put("title", "对手账号类型");
		formAction_editCTPY_ACCT_TYPE.put("dataset", "dsResult");
		formAction_editCTPY_ACCT_TYPE.put("name", "CTPY_ACCT_TYPE");
		formAction_editCTPY_ACCT_TYPE.put("moduleid", "RPT1308");
		formAction_editCTPY_ACCT_TYPE.put("bizCode", "0000");
		formAction_editCTPY_ACCT_TYPE.put("dropdownDataset", "");
		formAction_editCTPY_ACCT_TYPE.put("valueField", "");
		formAction_editCTPY_ACCT_TYPE.put("displayField", "");
		formAction_editCTPY_ACCT_TYPE.put("allowNull", "false");
		formAction_editCTPY_ACCT_TYPE.put("nullSelectionAllowed", "true");
		formAction_editCTPY_ACCT_TYPE.put("switchMode", "true");
		formAction_editCTPY_ACCT_TYPE.put("componentAlignment", "Middle_Left");
		formAction_editCTPY_ACCT_TYPE.put("columnStart", "5");
		formAction_editCTPY_ACCT_TYPE.put("columnEnd", "8");
		formAction_editCTPY_ACCT_TYPE.put("rowStart", "1");
		formAction_editCTPY_ACCT_TYPE.put("rowEnd", "1");
		formAction_editCTPY_ACCT_TYPE.put("colSpan", "");
		formAction_editCTPY_ACCT_TYPE.put("rowSpan", "");
		formAction_editCTPY_ACCT_TYPE.put("width", "100%");
		formAction_editCTPY_ACCT_TYPE.put("height", "");
		formAction_editCTPY_ACCT_TYPE.put("labelWidth", "");
		formAction_editCTPY_ACCT_TYPE.put("enable", "true");
		formAction_editCTPY_ACCT_TYPE.put("readOnly", "true");
		formAction_editCTPY_ACCT_TYPE.put("visible", "true");
		formAction_editCTPY_ACCT_TYPE.put("expandRatio", "");
		formAction_editCTPY_ACCT_TYPE.put("filteringMode", "Contains");
		formAction_editCTPY_ACCT_TYPE.put("attachComboBox", "");
		formAction_editCTPY_ACCT_TYPE.put("attachFieldName", "");
		formAction_editCTPY_ACCT_TYPE.put("leftColumnCaption", "");
		formAction_editCTPY_ACCT_TYPE.put("rightColumnCaption", "");
		formAction_editCTPY_ACCT_TYPE.put("isMultiSelect", "true");
		formAction_editCTPY_ACCT_TYPE.put("orientation", "vertical");
		formActionItemList.add(formAction_editCTPY_ACCT_TYPE);
		BaseConfig formAction_editCTPY_IC_TYPE = new BaseConfig();
		formAction_editCTPY_IC_TYPE.setXmlTag("FormItem");
		formAction_editCTPY_IC_TYPE.put("required", "true");
		formAction_editCTPY_IC_TYPE.put("requiredMessage", "");
		formAction_editCTPY_IC_TYPE.put("id", "editCTPY_IC_TYPE");
		formAction_editCTPY_IC_TYPE.put("fragmentId", "");
		formAction_editCTPY_IC_TYPE.put("type", "ComboBox");
		formAction_editCTPY_IC_TYPE.put("title", "对手证件类型");
		formAction_editCTPY_IC_TYPE.put("dataset", "dsResult");
		formAction_editCTPY_IC_TYPE.put("name", "CTPY_IC_TYPE");
		formAction_editCTPY_IC_TYPE.put("moduleid", "RPT1302");
		formAction_editCTPY_IC_TYPE.put("bizCode", "0000");
		formAction_editCTPY_IC_TYPE.put("dropdownDataset", "");
		formAction_editCTPY_IC_TYPE.put("valueField", "");
		formAction_editCTPY_IC_TYPE.put("displayField", "");
		formAction_editCTPY_IC_TYPE.put("allowNull", "false");
		formAction_editCTPY_IC_TYPE.put("nullSelectionAllowed", "true");
		formAction_editCTPY_IC_TYPE.put("switchMode", "true");
		formAction_editCTPY_IC_TYPE.put("componentAlignment", "Middle_Left");
		formAction_editCTPY_IC_TYPE.put("columnStart", "1");
		formAction_editCTPY_IC_TYPE.put("columnEnd", "4");
		formAction_editCTPY_IC_TYPE.put("rowStart", "2");
		formAction_editCTPY_IC_TYPE.put("rowEnd", "2");
		formAction_editCTPY_IC_TYPE.put("colSpan", "");
		formAction_editCTPY_IC_TYPE.put("rowSpan", "");
		formAction_editCTPY_IC_TYPE.put("width", "");
		formAction_editCTPY_IC_TYPE.put("height", "");
		formAction_editCTPY_IC_TYPE.put("labelWidth", "");
		formAction_editCTPY_IC_TYPE.put("enable", "true");
		formAction_editCTPY_IC_TYPE.put("readOnly", "true");
		formAction_editCTPY_IC_TYPE.put("visible", "true");
		formAction_editCTPY_IC_TYPE.put("expandRatio", "");
		formAction_editCTPY_IC_TYPE.put("filteringMode", "Contains");
		formAction_editCTPY_IC_TYPE.put("attachComboBox", "");
		formAction_editCTPY_IC_TYPE.put("attachFieldName", "");
		formAction_editCTPY_IC_TYPE.put("leftColumnCaption", "");
		formAction_editCTPY_IC_TYPE.put("rightColumnCaption", "");
		formAction_editCTPY_IC_TYPE.put("isMultiSelect", "true");
		formAction_editCTPY_IC_TYPE.put("orientation", "vertical");
		formActionItemList.add(formAction_editCTPY_IC_TYPE);
		BaseConfig formAction_editCTPY_IC_TYPE_MEMO = new BaseConfig();
		formAction_editCTPY_IC_TYPE_MEMO.setXmlTag("FormItem");
		formAction_editCTPY_IC_TYPE_MEMO.put("required", "false");
		formAction_editCTPY_IC_TYPE_MEMO.put("requiredMessage", "");
		formAction_editCTPY_IC_TYPE_MEMO.put("id", "editCTPY_IC_TYPE_MEMO");
		formAction_editCTPY_IC_TYPE_MEMO.put("fragmentId", "");
		formAction_editCTPY_IC_TYPE_MEMO.put("type", "Text");
		formAction_editCTPY_IC_TYPE_MEMO.put("leftMedian", "");
		formAction_editCTPY_IC_TYPE_MEMO.put("rightMedian", "");
		formAction_editCTPY_IC_TYPE_MEMO.put("title", "对手证件类型备注");
		formAction_editCTPY_IC_TYPE_MEMO.put("dataset", "dsResult");
		formAction_editCTPY_IC_TYPE_MEMO.put("name", "CTPY_IC_TYPE_MEMO");
		formAction_editCTPY_IC_TYPE_MEMO.put("resolution", "");
		formAction_editCTPY_IC_TYPE_MEMO.put("format", "");
		formAction_editCTPY_IC_TYPE_MEMO.put("picker", "");
		formAction_editCTPY_IC_TYPE_MEMO.put("componentAlignment", "Middle_Left");
		formAction_editCTPY_IC_TYPE_MEMO.put("labelAlignment", "Middle_Right");
		formAction_editCTPY_IC_TYPE_MEMO.put("columnStart", "5");
		formAction_editCTPY_IC_TYPE_MEMO.put("columnEnd", "8");
		formAction_editCTPY_IC_TYPE_MEMO.put("rowStart", "2");
		formAction_editCTPY_IC_TYPE_MEMO.put("rowEnd", "2");
		formAction_editCTPY_IC_TYPE_MEMO.put("columns", "");
		formAction_editCTPY_IC_TYPE_MEMO.put("rows", "");
		formAction_editCTPY_IC_TYPE_MEMO.put("colSpan", "");
		formAction_editCTPY_IC_TYPE_MEMO.put("rowSpan", "");
		formAction_editCTPY_IC_TYPE_MEMO.put("width", "100%");
		formAction_editCTPY_IC_TYPE_MEMO.put("height", "");
		formAction_editCTPY_IC_TYPE_MEMO.put("symbol", "");
		formAction_editCTPY_IC_TYPE_MEMO.put("maxLength", "");
		formAction_editCTPY_IC_TYPE_MEMO.put("labelWidth", "");
		formAction_editCTPY_IC_TYPE_MEMO.put("enable", "true");
		formAction_editCTPY_IC_TYPE_MEMO.put("readOnly", "true");
		formAction_editCTPY_IC_TYPE_MEMO.put("visible", "true");
		formAction_editCTPY_IC_TYPE_MEMO.put("dbcshortcut", "");
		formActionItemList.add(formAction_editCTPY_IC_TYPE_MEMO);
		BaseConfig formAction_editCTPY_IC_CODE = new BaseConfig();
		formAction_editCTPY_IC_CODE.setXmlTag("FormItem");
		formAction_editCTPY_IC_CODE.put("required", "true");
		formAction_editCTPY_IC_CODE.put("requiredMessage", "");
		formAction_editCTPY_IC_CODE.put("id", "editCTPY_IC_CODE");
		formAction_editCTPY_IC_CODE.put("fragmentId", "");
		formAction_editCTPY_IC_CODE.put("type", "Text");
		formAction_editCTPY_IC_CODE.put("leftMedian", "");
		formAction_editCTPY_IC_CODE.put("rightMedian", "");
		formAction_editCTPY_IC_CODE.put("title", "对手证件号码");
		formAction_editCTPY_IC_CODE.put("dataset", "dsResult");
		formAction_editCTPY_IC_CODE.put("name", "CTPY_IC_CODE");
		formAction_editCTPY_IC_CODE.put("resolution", "");
		formAction_editCTPY_IC_CODE.put("format", "");
		formAction_editCTPY_IC_CODE.put("picker", "");
		formAction_editCTPY_IC_CODE.put("componentAlignment", "Middle_Left");
		formAction_editCTPY_IC_CODE.put("labelAlignment", "Middle_Right");
		formAction_editCTPY_IC_CODE.put("columnStart", "1");
		formAction_editCTPY_IC_CODE.put("columnEnd", "4");
		formAction_editCTPY_IC_CODE.put("rowStart", "3");
		formAction_editCTPY_IC_CODE.put("rowEnd", "3");
		formAction_editCTPY_IC_CODE.put("columns", "");
		formAction_editCTPY_IC_CODE.put("rows", "");
		formAction_editCTPY_IC_CODE.put("colSpan", "");
		formAction_editCTPY_IC_CODE.put("rowSpan", "");
		formAction_editCTPY_IC_CODE.put("width", "100%");
		formAction_editCTPY_IC_CODE.put("height", "");
		formAction_editCTPY_IC_CODE.put("symbol", "");
		formAction_editCTPY_IC_CODE.put("maxLength", "");
		formAction_editCTPY_IC_CODE.put("labelWidth", "");
		formAction_editCTPY_IC_CODE.put("enable", "true");
		formAction_editCTPY_IC_CODE.put("readOnly", "true");
		formAction_editCTPY_IC_CODE.put("visible", "true");
		formAction_editCTPY_IC_CODE.put("dbcshortcut", "");
		formActionItemList.add(formAction_editCTPY_IC_CODE);
		BaseConfig formAction_editCTPY_NATIONALITY = new BaseConfig();
		formAction_editCTPY_NATIONALITY.setXmlTag("FormItem");
		formAction_editCTPY_NATIONALITY.put("required", "true");
		formAction_editCTPY_NATIONALITY.put("requiredMessage", "");
		formAction_editCTPY_NATIONALITY.put("id", "editCTPY_NATIONALITY");
		formAction_editCTPY_NATIONALITY.put("fragmentId", "");
		formAction_editCTPY_NATIONALITY.put("type", "Text");
		formAction_editCTPY_NATIONALITY.put("leftMedian", "");
		formAction_editCTPY_NATIONALITY.put("rightMedian", "");
		formAction_editCTPY_NATIONALITY.put("title", "对手国籍");
		formAction_editCTPY_NATIONALITY.put("dataset", "dsResult");
		formAction_editCTPY_NATIONALITY.put("name", "CTPY_NATIONALITY");
		formAction_editCTPY_NATIONALITY.put("resolution", "");
		formAction_editCTPY_NATIONALITY.put("format", "");
		formAction_editCTPY_NATIONALITY.put("picker", "S");
		formAction_editCTPY_NATIONALITY.put("componentAlignment", "Middle_Left");
		formAction_editCTPY_NATIONALITY.put("labelAlignment", "Middle_Right");
		formAction_editCTPY_NATIONALITY.put("columnStart", "5");
		formAction_editCTPY_NATIONALITY.put("columnEnd", "8");
		formAction_editCTPY_NATIONALITY.put("rowStart", "3");
		formAction_editCTPY_NATIONALITY.put("rowEnd", "3");
		formAction_editCTPY_NATIONALITY.put("columns", "");
		formAction_editCTPY_NATIONALITY.put("rows", "");
		formAction_editCTPY_NATIONALITY.put("colSpan", "");
		formAction_editCTPY_NATIONALITY.put("rowSpan", "");
		formAction_editCTPY_NATIONALITY.put("width", "100%");
		formAction_editCTPY_NATIONALITY.put("height", "");
		formAction_editCTPY_NATIONALITY.put("symbol", "");
		formAction_editCTPY_NATIONALITY.put("maxLength", "");
		formAction_editCTPY_NATIONALITY.put("labelWidth", "");
		formAction_editCTPY_NATIONALITY.put("enable", "true");
		formAction_editCTPY_NATIONALITY.put("readOnly", "true");
		formAction_editCTPY_NATIONALITY.put("visible", "true");
		formAction_editCTPY_NATIONALITY.put("dbcshortcut", "");
		formActionItemList.add(formAction_editCTPY_NATIONALITY);
		BaseConfig formAction_editCTPY_TYPE = new BaseConfig();
		formAction_editCTPY_TYPE.setXmlTag("FormItem");
		formAction_editCTPY_TYPE.put("required", "true");
		formAction_editCTPY_TYPE.put("requiredMessage", "");
		formAction_editCTPY_TYPE.put("id", "editCTPY_TYPE");
		formAction_editCTPY_TYPE.put("fragmentId", "");
		formAction_editCTPY_TYPE.put("type", "ComboBox");
		formAction_editCTPY_TYPE.put("title", "对手类型");
		formAction_editCTPY_TYPE.put("dataset", "dsResult");
		formAction_editCTPY_TYPE.put("name", "CTPY_TYPE");
		formAction_editCTPY_TYPE.put("moduleid", "RPT1301");
		formAction_editCTPY_TYPE.put("bizCode", "0000");
		formAction_editCTPY_TYPE.put("dropdownDataset", "");
		formAction_editCTPY_TYPE.put("valueField", "");
		formAction_editCTPY_TYPE.put("displayField", "");
		formAction_editCTPY_TYPE.put("allowNull", "false");
		formAction_editCTPY_TYPE.put("nullSelectionAllowed", "true");
		formAction_editCTPY_TYPE.put("switchMode", "true");
		formAction_editCTPY_TYPE.put("componentAlignment", "Middle_Left");
		formAction_editCTPY_TYPE.put("columnStart", "1");
		formAction_editCTPY_TYPE.put("columnEnd", "4");
		formAction_editCTPY_TYPE.put("rowStart", "4");
		formAction_editCTPY_TYPE.put("rowEnd", "4");
		formAction_editCTPY_TYPE.put("colSpan", "");
		formAction_editCTPY_TYPE.put("rowSpan", "");
		formAction_editCTPY_TYPE.put("width", "100%");
		formAction_editCTPY_TYPE.put("height", "");
		formAction_editCTPY_TYPE.put("labelWidth", "");
		formAction_editCTPY_TYPE.put("enable", "true");
		formAction_editCTPY_TYPE.put("readOnly", "true");
		formAction_editCTPY_TYPE.put("visible", "true");
		formAction_editCTPY_TYPE.put("expandRatio", "");
		formAction_editCTPY_TYPE.put("filteringMode", "Contains");
		formAction_editCTPY_TYPE.put("attachComboBox", "");
		formAction_editCTPY_TYPE.put("attachFieldName", "");
		formAction_editCTPY_TYPE.put("leftColumnCaption", "");
		formAction_editCTPY_TYPE.put("rightColumnCaption", "");
		formAction_editCTPY_TYPE.put("isMultiSelect", "true");
		formAction_editCTPY_TYPE.put("orientation", "vertical");
		formActionItemList.add(formAction_editCTPY_TYPE);
		BaseConfig formAction_editCTPY_NAME = new BaseConfig();
		formAction_editCTPY_NAME.setXmlTag("FormItem");
		formAction_editCTPY_NAME.put("required", "true");
		formAction_editCTPY_NAME.put("requiredMessage", "");
		formAction_editCTPY_NAME.put("id", "editCTPY_NAME");
		formAction_editCTPY_NAME.put("fragmentId", "");
		formAction_editCTPY_NAME.put("type", "Text");
		formAction_editCTPY_NAME.put("leftMedian", "");
		formAction_editCTPY_NAME.put("rightMedian", "");
		formAction_editCTPY_NAME.put("title", "对手名称");
		formAction_editCTPY_NAME.put("dataset", "dsResult");
		formAction_editCTPY_NAME.put("name", "CTPY_NAME");
		formAction_editCTPY_NAME.put("resolution", "");
		formAction_editCTPY_NAME.put("format", "");
		formAction_editCTPY_NAME.put("picker", "");
		formAction_editCTPY_NAME.put("componentAlignment", "Middle_Left");
		formAction_editCTPY_NAME.put("labelAlignment", "Middle_Right");
		formAction_editCTPY_NAME.put("columnStart", "5");
		formAction_editCTPY_NAME.put("columnEnd", "8");
		formAction_editCTPY_NAME.put("rowStart", "4");
		formAction_editCTPY_NAME.put("rowEnd", "4");
		formAction_editCTPY_NAME.put("columns", "");
		formAction_editCTPY_NAME.put("rows", "");
		formAction_editCTPY_NAME.put("colSpan", "");
		formAction_editCTPY_NAME.put("rowSpan", "");
		formAction_editCTPY_NAME.put("width", "100%");
		formAction_editCTPY_NAME.put("height", "");
		formAction_editCTPY_NAME.put("symbol", "");
		formAction_editCTPY_NAME.put("maxLength", "");
		formAction_editCTPY_NAME.put("labelWidth", "");
		formAction_editCTPY_NAME.put("enable", "true");
		formAction_editCTPY_NAME.put("readOnly", "true");
		formAction_editCTPY_NAME.put("visible", "true");
		formAction_editCTPY_NAME.put("dbcshortcut", "");
		formActionItemList.add(formAction_editCTPY_NAME);
		formAction.put("formItemList",formActionItemList);
		return formAction;
	}

	private BaseConfig sub_control_outerLayout() {
		BaseConfig outerLayout = new BaseConfig();
		outerLayout.setXmlTag("Layout");
		outerLayout.put("id", "outerLayout");
		outerLayout.put("fragmentId", "");
		outerLayout.put("type", "VFlow");
		outerLayout.put("row", "");
		outerLayout.put("column", "");
		outerLayout.put("labelAlign", "left");
		outerLayout.put("componentAlignment", "Middle_Left");
		outerLayout.put("margin", "false");
		outerLayout.put("spacing", "false");
		outerLayout.put("columnExpandRatio", "");
		outerLayout.put("width", "");
		outerLayout.put("height", "");
		outerLayout.put("enable", "true");
		outerLayout.put("readOnly", "false");
		outerLayout.put("visible", "true");
		List<BaseConfig> outerLayoutList = new ArrayList<BaseConfig>();
		outerLayout.put("outerLayoutList",outerLayoutList);
		BaseConfig queryForm = sub_control_queryForm();
		outerLayoutList.add(queryForm);
		BaseConfig queryBtnLayout = sub_control_queryBtnLayout();
		outerLayoutList.add(queryBtnLayout);
		BaseConfig tableResult = sub_control_tableResult();
		outerLayoutList.add(tableResult);
		BaseConfig paginglayout = sub_control_paginglayout();
		outerLayoutList.add(paginglayout);
		BaseConfig btnLayout = sub_control_btnLayout();
		outerLayoutList.add(btnLayout);
		BaseConfig formAction = sub_control_formAction();
		outerLayoutList.add(formAction);
		return outerLayout;
	}

	private BaseConfig sub_control_countryQueryForm() {
		BaseConfig countryQueryForm = new BaseConfig();
		countryQueryForm.setXmlTag("Form");
		countryQueryForm.put("id", "countryQueryForm");
		countryQueryForm.put("fragmentId", "");
		countryQueryForm.put("type", "Auto");
		countryQueryForm.put("title", "国家地区");
		countryQueryForm.put("dataset", "dsCountryQuery");
		countryQueryForm.put("width", "600px");
		countryQueryForm.put("height", "");
		countryQueryForm.put("enable", "true");
		countryQueryForm.put("readOnly", "false");
		countryQueryForm.put("visible", "true");
		countryQueryForm.put("expandRatio", "");
		countryQueryForm.put("numCols", "4");
		List<BaseConfig> countryQueryFormItemList = new ArrayList<BaseConfig>();
		BaseConfig countryQueryForm_countryCode = new BaseConfig();
		countryQueryForm_countryCode.setXmlTag("FormItem");
		countryQueryForm_countryCode.put("required", "false");
		countryQueryForm_countryCode.put("requiredMessage", "");
		countryQueryForm_countryCode.put("id", "countryCode");
		countryQueryForm_countryCode.put("fragmentId", "");
		countryQueryForm_countryCode.put("type", "Text");
		countryQueryForm_countryCode.put("leftMedian", "");
		countryQueryForm_countryCode.put("rightMedian", "");
		countryQueryForm_countryCode.put("title", "国家地区代码");
		countryQueryForm_countryCode.put("dataset", "dsCountryQuery");
		countryQueryForm_countryCode.put("name", "countryCode");
		countryQueryForm_countryCode.put("resolution", "");
		countryQueryForm_countryCode.put("format", "");
		countryQueryForm_countryCode.put("picker", "");
		countryQueryForm_countryCode.put("componentAlignment", "Middle_Left");
		countryQueryForm_countryCode.put("labelAlignment", "Middle_Right");
		countryQueryForm_countryCode.put("columnStart", "1");
		countryQueryForm_countryCode.put("columnEnd", "4");
		countryQueryForm_countryCode.put("rowStart", "1");
		countryQueryForm_countryCode.put("rowEnd", "1");
		countryQueryForm_countryCode.put("columns", "");
		countryQueryForm_countryCode.put("rows", "");
		countryQueryForm_countryCode.put("colSpan", "");
		countryQueryForm_countryCode.put("rowSpan", "");
		countryQueryForm_countryCode.put("width", "100%");
		countryQueryForm_countryCode.put("height", "");
		countryQueryForm_countryCode.put("symbol", "");
		countryQueryForm_countryCode.put("maxLength", "");
		countryQueryForm_countryCode.put("labelWidth", "");
		countryQueryForm_countryCode.put("enable", "true");
		countryQueryForm_countryCode.put("readOnly", "false");
		countryQueryForm_countryCode.put("visible", "true");
		countryQueryForm_countryCode.put("dbcshortcut", "");
		countryQueryFormItemList.add(countryQueryForm_countryCode);
		BaseConfig countryQueryForm_countryName = new BaseConfig();
		countryQueryForm_countryName.setXmlTag("FormItem");
		countryQueryForm_countryName.put("required", "false");
		countryQueryForm_countryName.put("requiredMessage", "");
		countryQueryForm_countryName.put("id", "countryName");
		countryQueryForm_countryName.put("fragmentId", "");
		countryQueryForm_countryName.put("type", "Text");
		countryQueryForm_countryName.put("leftMedian", "");
		countryQueryForm_countryName.put("rightMedian", "");
		countryQueryForm_countryName.put("title", "国家地区名称");
		countryQueryForm_countryName.put("dataset", "dsCountryQuery");
		countryQueryForm_countryName.put("name", "countryName");
		countryQueryForm_countryName.put("resolution", "");
		countryQueryForm_countryName.put("format", "");
		countryQueryForm_countryName.put("picker", "");
		countryQueryForm_countryName.put("componentAlignment", "Middle_Left");
		countryQueryForm_countryName.put("labelAlignment", "Middle_Right");
		countryQueryForm_countryName.put("columnStart", "5");
		countryQueryForm_countryName.put("columnEnd", "8");
		countryQueryForm_countryName.put("rowStart", "1");
		countryQueryForm_countryName.put("rowEnd", "1");
		countryQueryForm_countryName.put("columns", "");
		countryQueryForm_countryName.put("rows", "");
		countryQueryForm_countryName.put("colSpan", "");
		countryQueryForm_countryName.put("rowSpan", "");
		countryQueryForm_countryName.put("width", "100%");
		countryQueryForm_countryName.put("height", "");
		countryQueryForm_countryName.put("symbol", "");
		countryQueryForm_countryName.put("maxLength", "");
		countryQueryForm_countryName.put("labelWidth", "");
		countryQueryForm_countryName.put("enable", "true");
		countryQueryForm_countryName.put("readOnly", "false");
		countryQueryForm_countryName.put("visible", "true");
		countryQueryForm_countryName.put("dbcshortcut", "");
		countryQueryFormItemList.add(countryQueryForm_countryName);
		countryQueryForm.put("formItemList",countryQueryFormItemList);
		return countryQueryForm;
	}

	private BaseConfig sub_control_btnCountryQuery() {
		BaseConfig btnCountryQuery = new BaseConfig();
		btnCountryQuery.setXmlTag("Button");
		btnCountryQuery.put("id", "btnCountryQuery");
		btnCountryQuery.put("fragmentId", "");
		btnCountryQuery.put("type", "Base");
		btnCountryQuery.put("title", "查询");
		btnCountryQuery.put("width", "");
		btnCountryQuery.put("height", "");
		btnCountryQuery.put("componentAlignment", "Middle_Left");
		btnCountryQuery.put("command", "");
		btnCountryQuery.put("callbackCommand", "");
		btnCountryQuery.put("columnStart", "9");
		btnCountryQuery.put("columnEnd", "12");
		btnCountryQuery.put("rowStart", "1");
		btnCountryQuery.put("rowEnd", "1");
		btnCountryQuery.put("enable", "true");
		btnCountryQuery.put("readOnly", "false");
		btnCountryQuery.put("visible", "true");
		btnCountryQuery.put("expandRatio", "");
		btnCountryQuery.put("shortcut", "");
		return btnCountryQuery;
	}

	private BaseConfig sub_control_btnCountryOk() {
		BaseConfig btnCountryOk = new BaseConfig();
		btnCountryOk.setXmlTag("Button");
		btnCountryOk.put("id", "btnCountryOk");
		btnCountryOk.put("fragmentId", "");
		btnCountryOk.put("type", "Base");
		btnCountryOk.put("title", "确定");
		btnCountryOk.put("width", "");
		btnCountryOk.put("height", "");
		btnCountryOk.put("componentAlignment", "");
		btnCountryOk.put("command", "");
		btnCountryOk.put("callbackCommand", "");
		btnCountryOk.put("columnStart", "");
		btnCountryOk.put("columnEnd", "");
		btnCountryOk.put("rowStart", "");
		btnCountryOk.put("rowEnd", "");
		btnCountryOk.put("enable", "true");
		btnCountryOk.put("readOnly", "false");
		btnCountryOk.put("visible", "true");
		btnCountryOk.put("expandRatio", "");
		btnCountryOk.put("shortcut", "");
		return btnCountryOk;
	}

	private BaseConfig sub_control_btnCountryBack() {
		BaseConfig btnCountryBack = new BaseConfig();
		btnCountryBack.setXmlTag("Button");
		btnCountryBack.put("id", "btnCountryBack");
		btnCountryBack.put("fragmentId", "");
		btnCountryBack.put("type", "Base");
		btnCountryBack.put("title", "返回");
		btnCountryBack.put("width", "");
		btnCountryBack.put("height", "");
		btnCountryBack.put("componentAlignment", "");
		btnCountryBack.put("command", "");
		btnCountryBack.put("callbackCommand", "");
		btnCountryBack.put("columnStart", "");
		btnCountryBack.put("columnEnd", "");
		btnCountryBack.put("rowStart", "");
		btnCountryBack.put("rowEnd", "");
		btnCountryBack.put("enable", "true");
		btnCountryBack.put("readOnly", "false");
		btnCountryBack.put("visible", "true");
		btnCountryBack.put("expandRatio", "");
		btnCountryBack.put("shortcut", "");
		return btnCountryBack;
	}

	private BaseConfig sub_control_btnCountryLayout() {
		BaseConfig btnCountryLayout = new BaseConfig();
		btnCountryLayout.setXmlTag("Layout");
		btnCountryLayout.put("id", "btnCountryLayout");
		btnCountryLayout.put("fragmentId", "");
		btnCountryLayout.put("type", "HFlow");
		btnCountryLayout.put("row", "");
		btnCountryLayout.put("column", "");
		btnCountryLayout.put("labelAlign", "left");
		btnCountryLayout.put("componentAlignment", "Top_Left");
		btnCountryLayout.put("margin", "false");
		btnCountryLayout.put("spacing", "false");
		btnCountryLayout.put("columnExpandRatio", "");
		btnCountryLayout.put("width", "");
		btnCountryLayout.put("height", "");
		btnCountryLayout.put("enable", "true");
		btnCountryLayout.put("readOnly", "false");
		btnCountryLayout.put("visible", "true");
		List<BaseConfig> btnCountryLayoutList = new ArrayList<BaseConfig>();
		btnCountryLayout.put("btnCountryLayoutList",btnCountryLayoutList);
		BaseConfig btnCountryQuery = sub_control_btnCountryQuery();
		btnCountryLayoutList.add(btnCountryQuery);
		BaseConfig btnCountryOk = sub_control_btnCountryOk();
		btnCountryLayoutList.add(btnCountryOk);
		BaseConfig btnCountryBack = sub_control_btnCountryBack();
		btnCountryLayoutList.add(btnCountryBack);
		return btnCountryLayout;
	}

	private BaseConfig sub_control_tableCountryResult() {
		BaseConfig tableCountryResult = new BaseConfig();
		tableCountryResult.setXmlTag("Table");
		tableCountryResult.put("id", "tableCountryResult");
		tableCountryResult.put("fragmentId", "");
		tableCountryResult.put("type", "Base");
		tableCountryResult.put("caption", "");
		tableCountryResult.put("hightLight", "true");
		tableCountryResult.put("dataset", "dsCountryResult");
		tableCountryResult.put("width", "600px");
		tableCountryResult.put("height", "200px");
		tableCountryResult.put("enable", "true");
		tableCountryResult.put("readOnly", "false");
		tableCountryResult.put("visible", "true");
		tableCountryResult.put("selectField", "");
		tableCountryResult.put("reorderingAllowed", "false");
		tableCountryResult.put("collapsingAllowed", "false");
		tableCountryResult.put("expandRatio", "");
		List<BaseConfig> tableCountryResultFieldList = new ArrayList<BaseConfig>();
		BaseConfig colCountryCode = new BaseConfig();
		colCountryCode.setXmlTag("ListGridField");
		colCountryCode.put("type", "Base");
		colCountryCode.put("name", "countryCode");
		colCountryCode.put("id", "colCountryCode");
		colCountryCode.put("field", "countryCode");
		colCountryCode.put("title", "国家地区代码");
		colCountryCode.put("moduleid", "");
		colCountryCode.put("bizCode", "");
		colCountryCode.put("dropdown", "");
		colCountryCode.put("dateFormat", "");
		colCountryCode.put("moneyFormat", "");
		colCountryCode.put("width", "");
		colCountryCode.put("columnAlignment", "Align_left");
		colCountryCode.put("enable", "true");
		colCountryCode.put("readOnly", "false");
		colCountryCode.put("visible", "true");
		colCountryCode.put("addUp", "false");
		tableCountryResultFieldList.add(colCountryCode);
		BaseConfig colCountryName = new BaseConfig();
		colCountryName.setXmlTag("ListGridField");
		colCountryName.put("type", "Base");
		colCountryName.put("name", "countryName");
		colCountryName.put("id", "colCountryName");
		colCountryName.put("field", "countryName");
		colCountryName.put("title", "国家地区名称");
		colCountryName.put("moduleid", "");
		colCountryName.put("bizCode", "");
		colCountryName.put("dropdown", "");
		colCountryName.put("dateFormat", "");
		colCountryName.put("moneyFormat", "");
		colCountryName.put("width", "");
		colCountryName.put("columnAlignment", "Align_left");
		colCountryName.put("enable", "true");
		colCountryName.put("readOnly", "false");
		colCountryName.put("visible", "true");
		colCountryName.put("addUp", "false");
		tableCountryResultFieldList.add(colCountryName);
		tableCountryResult.put("tableFieldConfigList",tableCountryResultFieldList);
		return tableCountryResult;
	}

	private BaseConfig sub_control_pagebarCountry() {
		BaseConfig pagebarCountry = new BaseConfig();
		pagebarCountry.setXmlTag("Navigation");
		pagebarCountry.put("id", "pagebarCountry");
		pagebarCountry.put("fragmentId", "");
		pagebarCountry.put("type", "Pagebar");
		pagebarCountry.put("dataset", "dsCountryResult");
		pagebarCountry.put("showPagesize", "false");
		pagebarCountry.put("showFirstAndLast", "true");
		pagebarCountry.put("showRefresh", "true");
		pagebarCountry.put("showDetail", "true");
		pagebarCountry.put("showTotalCount", "true");
		pagebarCountry.put("enable", "true");
		pagebarCountry.put("readOnly", "false");
		pagebarCountry.put("visible", "true");
		return pagebarCountry;
	}

	private BaseConfig sub_control_pagingCountrylayout() {
		BaseConfig pagingCountrylayout = new BaseConfig();
		pagingCountrylayout.setXmlTag("Layout");
		pagingCountrylayout.put("id", "pagingCountrylayout");
		pagingCountrylayout.put("fragmentId", "");
		pagingCountrylayout.put("type", "HFlow");
		pagingCountrylayout.put("row", "");
		pagingCountrylayout.put("column", "");
		pagingCountrylayout.put("labelAlign", "left");
		pagingCountrylayout.put("componentAlignment", "Middle_Right");
		pagingCountrylayout.put("margin", "false");
		pagingCountrylayout.put("spacing", "false");
		pagingCountrylayout.put("columnExpandRatio", "");
		pagingCountrylayout.put("width", "600px");
		pagingCountrylayout.put("height", "");
		pagingCountrylayout.put("enable", "true");
		pagingCountrylayout.put("readOnly", "false");
		pagingCountrylayout.put("visible", "true");
		List<BaseConfig> pagingCountrylayoutList = new ArrayList<BaseConfig>();
		pagingCountrylayout.put("pagingCountrylayoutList",pagingCountrylayoutList);
		BaseConfig pagebarCountry = sub_control_pagebarCountry();
		pagingCountrylayoutList.add(pagebarCountry);
		return pagingCountrylayout;
	}

	private BaseConfig sub_control_tabCountryLayout() {
		BaseConfig tabCountryLayout = new BaseConfig();
		tabCountryLayout.setXmlTag("Layout");
		tabCountryLayout.put("id", "tabCountryLayout");
		tabCountryLayout.put("fragmentId", "");
		tabCountryLayout.put("type", "VFlow");
		tabCountryLayout.put("row", "");
		tabCountryLayout.put("column", "");
		tabCountryLayout.put("labelAlign", "left");
		tabCountryLayout.put("componentAlignment", "Top_Left");
		tabCountryLayout.put("margin", "false");
		tabCountryLayout.put("spacing", "false");
		tabCountryLayout.put("columnExpandRatio", "");
		tabCountryLayout.put("width", "");
		tabCountryLayout.put("height", "");
		tabCountryLayout.put("enable", "true");
		tabCountryLayout.put("readOnly", "false");
		tabCountryLayout.put("visible", "true");
		List<BaseConfig> tabCountryLayoutList = new ArrayList<BaseConfig>();
		tabCountryLayout.put("tabCountryLayoutList",tabCountryLayoutList);
		BaseConfig countryQueryForm = sub_control_countryQueryForm();
		tabCountryLayoutList.add(countryQueryForm);
		BaseConfig btnCountryLayout = sub_control_btnCountryLayout();
		tabCountryLayoutList.add(btnCountryLayout);
		BaseConfig tableCountryResult = sub_control_tableCountryResult();
		tabCountryLayoutList.add(tableCountryResult);
		BaseConfig pagingCountrylayout = sub_control_pagingCountrylayout();
		tabCountryLayoutList.add(pagingCountrylayout);
		return tabCountryLayout;
	}

	private BaseConfig sub_control_countryWindow() {
		BaseConfig countryWindow = new BaseConfig();
		countryWindow.setXmlTag("Window");
		countryWindow.put("id", "countryWindow");
		countryWindow.put("fragmentId", "");
		countryWindow.put("type", "Sub");
		countryWindow.put("title", "国籍选择");
		countryWindow.put("closeable", "true");
		countryWindow.put("draggable", "false");
		countryWindow.put("resizeable", "false");
		countryWindow.put("shortcut", "");
		countryWindow.put("modal", "false");
		countryWindow.put("autoCenter", "true");
		countryWindow.put("autoSize", "true");
		countryWindow.put("positionX", "0");
		countryWindow.put("positionY", "0");
		countryWindow.put("border", "1");
		countryWindow.put("width", "");
		countryWindow.put("height", "");
		countryWindow.put("enable", "true");
		countryWindow.put("readOnly", "false");
		countryWindow.put("visible", "true");
		List<BaseConfig> countryWindowList = new ArrayList<BaseConfig>();
		countryWindow.put("countryWindowList",countryWindowList);
		BaseConfig tabCountryLayout = sub_control_tabCountryLayout();
		countryWindowList.add(tabCountryLayout);
		return countryWindow;
	}

	@Override
	protected void afterInitControls() {
		super.afterInitControls();
		dsQuery = (ViewDataset)this.getDatasets().get("dsQuery");
		dsResult = (ViewDataset)this.getDatasets().get("dsResult");
		dsCountryQuery = (ViewDataset)this.getDatasets().get("dsCountryQuery");
		dsCountryResult = (ViewDataset)this.getDatasets().get("dsCountryResult");
		queryCmd = (DatasetCommand)this.getCommands().get("queryCmd");
		saveCmd = (DatasetCommand)this.getCommands().get("saveCmd");
		qryCountryCmd = (DatasetCommand)this.getCommands().get("qryCountryCmd");
		queryForm = (UDynamicForm)this.getControls().get("queryForm");
		editorCTPY_ACCT_ID = (UTextItem)((UDynamicForm)this.getControls().get("queryForm")).getField("CTPY_ACCT_ID");
		editorCTPY_NAME = (UTextItem)((UDynamicForm)this.getControls().get("queryForm")).getField("CTPY_NAME");
		btnQuery = (UButton)this.getControls().get("btnQuery");
		tableResult = (UTable)this.getControls().get("tableResult");
		btnAdd = (UButton)this.getControls().get("btnAdd");
		btnMod = (UButton)this.getControls().get("btnMod");
		btnDel = (UButton)this.getControls().get("btnDel");
		btnSave = (UButton)this.getControls().get("btnSave");
		btnCancel = (UButton)this.getControls().get("btnCancel");
		formAction = (UDynamicForm)this.getControls().get("formAction");
		editCTPY_ACCT_ID = (UTextItem)((UDynamicForm)this.getControls().get("formAction")).getField("CTPY_ACCT_ID");
		editCTPY_ACCT_TYPE = (USelectItem)((UDynamicForm)this.getControls().get("formAction")).getField("CTPY_ACCT_TYPE");
		editCTPY_IC_TYPE = (USelectItem)((UDynamicForm)this.getControls().get("formAction")).getField("CTPY_IC_TYPE");
		editCTPY_IC_TYPE_MEMO = (UTextItem)((UDynamicForm)this.getControls().get("formAction")).getField("CTPY_IC_TYPE_MEMO");
		editCTPY_IC_CODE = (UTextItem)((UDynamicForm)this.getControls().get("formAction")).getField("CTPY_IC_CODE");
		editCTPY_NATIONALITY = (UTextItem)((UDynamicForm)this.getControls().get("formAction")).getField("CTPY_NATIONALITY");
		editCTPY_TYPE = (USelectItem)((UDynamicForm)this.getControls().get("formAction")).getField("CTPY_TYPE");
		editCTPY_NAME = (UTextItem)((UDynamicForm)this.getControls().get("formAction")).getField("CTPY_NAME");
		countryWindow = (UWindow)this.getControls().get("countryWindow");
		countryQueryForm = (UDynamicForm)this.getControls().get("countryQueryForm");
		countryCode = (UTextItem)((UDynamicForm)this.getControls().get("countryQueryForm")).getField("countryCode");
		countryName = (UTextItem)((UDynamicForm)this.getControls().get("countryQueryForm")).getField("countryName");
		btnCountryQuery = (UButton)this.getControls().get("btnCountryQuery");
		btnCountryOk = (UButton)this.getControls().get("btnCountryOk");
		btnCountryBack = (UButton)this.getControls().get("btnCountryBack");
		tableCountryResult = (UTable)this.getControls().get("tableCountryResult");
		return;
	}
}