-- 8、文件类型
-- select BANK, APPLICATION, GROUP_CODE, GROUP_NAME, META_VAL, META_NAME, CREATOR, CREATE_TIME, MOD_USER, MOD_DATE, ENABLE, REMARK, MOD_ABLE from TB_DICT where GROUP_NAME='文件类型';
-- select * from TB_DICT where GROUP_NAME='银行卡类型';
--         文件类型修改为 新增N、修改C、删除D 三类
-- ('0000','RPT','2117','文件类型','A','新增文件','','','','','1','','1')
update TB_DICT set META_NAME='新增文件' where BANK='0000' and APPLICATION='RPT' and GROUP_CODE='2117' and META_VAL='N';
update TB_DICT set META_NAME='修改文件' where BANK='0000' and APPLICATION='RPT' and GROUP_CODE='2117' and META_VAL='C';
delete from TB_DICT where BANK='0000' and APPLICATION='RPT' and GROUP_CODE='2117' and META_VAL='A';
delete from TB_DICT where BANK='0000' and APPLICATION='RPT' and GROUP_CODE='2117' and META_VAL='I';
delete from TB_DICT where BANK='0000' and APPLICATION='RPT' and GROUP_CODE='2117' and META_VAL='R';

-- 9、收付款方匹配号类型
-- 新增收付款方匹配号类型基础数据
-- select * from TB_DICT where GROUP_NAME='收付款方匹配号类型';
insert into TB_DICT (BANK, APPLICATION, GROUP_CODE, GROUP_NAME, META_VAL, META_NAME, CREATOR, CREATE_TIME, MOD_USER, MOD_DATE, ENABLE, REMARK, MOD_ABLE) VALUES ('0000','RPT','8421','收付款方匹配号类型','01','通过大小额支付系统和超级网银清算的交易',NULL,NULL,NULL,NULL,'1',NULL,'1');
insert into TB_DICT (BANK, APPLICATION, GROUP_CODE, GROUP_NAME, META_VAL, META_NAME, CREATOR, CREATE_TIME, MOD_USER, MOD_DATE, ENABLE, REMARK, MOD_ABLE) VALUES ('0000','RPT','8421','收付款方匹配号类型','02','通过银联清算的交易',NULL,NULL,NULL,NULL,'1',NULL,'1');
insert into TB_DICT (BANK, APPLICATION, GROUP_CODE, GROUP_NAME, META_VAL, META_NAME, CREATOR, CREATE_TIME, MOD_USER, MOD_DATE, ENABLE, REMARK, MOD_ABLE) VALUES ('0000','RPT','8421','收付款方匹配号类型','03','通过外汇交易系统的交易',NULL,NULL,NULL,NULL,'1',NULL,'1');
insert into TB_DICT (BANK, APPLICATION, GROUP_CODE, GROUP_NAME, META_VAL, META_NAME, CREATOR, CREATE_TIME, MOD_USER, MOD_DATE, ENABLE, REMARK, MOD_ABLE) VALUES ('0000','RPT','8421','收付款方匹配号类型','04','金融机构内部交易',NULL,NULL,NULL,NULL,'1',NULL,'1');
insert into TB_DICT (BANK, APPLICATION, GROUP_CODE, GROUP_NAME, META_VAL, META_NAME, CREATOR, CREATE_TIME, MOD_USER, MOD_DATE, ENABLE, REMARK, MOD_ABLE) VALUES ('0000','RPT','8421','收付款方匹配号类型','05','通过城市商业银行资金清算中心清算的交易',NULL,NULL,NULL,NULL,'1',NULL,'1');
insert into TB_DICT (BANK, APPLICATION, GROUP_CODE, GROUP_NAME, META_VAL, META_NAME, CREATOR, CREATE_TIME, MOD_USER, MOD_DATE, ENABLE, REMARK, MOD_ABLE) VALUES ('0000','RPT','8421','收付款方匹配号类型','06','通过农信银资金清算中心清算的交易',NULL,NULL,NULL,NULL,'1',NULL,'1');
insert into TB_DICT (BANK, APPLICATION, GROUP_CODE, GROUP_NAME, META_VAL, META_NAME, CREATOR, CREATE_TIME, MOD_USER, MOD_DATE, ENABLE, REMARK, MOD_ABLE) VALUES ('0000','RPT','8421','收付款方匹配号类型','11','票据清算',NULL,NULL,NULL,NULL,'1',NULL,'1');

-- 10、疑似涉罪类型
-- 新增疑似涉罪类型基础数据
-- select * from TB_DICT where GROUP_NAME='疑似涉罪类型';
-- delete from TB_DICT where BANK='0000' and APPLICATION='RPT' and GROUP_CODE='8422' and META_VAL='0502';

insert into TB_DICT (BANK, APPLICATION, GROUP_CODE, GROUP_NAME, META_VAL, META_NAME, CREATOR, CREATE_TIME, MOD_USER, MOD_DATE, ENABLE, REMARK, MOD_ABLE) VALUES ('0000','RPT','8422','疑似涉罪类型','0101','涉嫌与毒品犯罪相关的可疑交易行为',NULL,NULL,NULL,NULL,'1',NULL,'1');
insert into TB_DICT (BANK, APPLICATION, GROUP_CODE, GROUP_NAME, META_VAL, META_NAME, CREATOR, CREATE_TIME, MOD_USER, MOD_DATE, ENABLE, REMARK, MOD_ABLE) VALUES ('0000','RPT','8422','疑似涉罪类型','0201','涉嫌与黑社会性质组织犯罪相关的可疑交易行为',NULL,NULL,NULL,NULL,'1',NULL,'1');
insert into TB_DICT (BANK, APPLICATION, GROUP_CODE, GROUP_NAME, META_VAL, META_NAME, CREATOR, CREATE_TIME, MOD_USER, MOD_DATE, ENABLE, REMARK, MOD_ABLE) VALUES ('0000','RPT','8422','疑似涉罪类型','0301','涉嫌与恐怖主义活动犯罪相关的可疑交易行为',NULL,NULL,NULL,NULL,'1',NULL,'1');
insert into TB_DICT (BANK, APPLICATION, GROUP_CODE, GROUP_NAME, META_VAL, META_NAME, CREATOR, CREATE_TIME, MOD_USER, MOD_DATE, ENABLE, REMARK, MOD_ABLE) VALUES ('0000','RPT','8422','疑似涉罪类型','0401','涉嫌与走私犯罪相关的可疑交易行为',NULL,NULL,NULL,NULL,'1',NULL,'1');
insert into TB_DICT (BANK, APPLICATION, GROUP_CODE, GROUP_NAME, META_VAL, META_NAME, CREATOR, CREATE_TIME, MOD_USER, MOD_DATE, ENABLE, REMARK, MOD_ABLE) VALUES ('0000','RPT','8422','疑似涉罪类型','0501','涉嫌行贿、受贿的可疑交易行为',NULL,NULL,NULL,NULL,'1',NULL,'1');
insert into TB_DICT (BANK, APPLICATION, GROUP_CODE, GROUP_NAME, META_VAL, META_NAME, CREATOR, CREATE_TIME, MOD_USER, MOD_DATE, ENABLE, REMARK, MOD_ABLE) VALUES ('0000','RPT','8422','疑似涉罪类型','0502','涉嫌从事与其公职人员或其亲属身份不符的可疑交易行为',NULL,NULL,NULL,NULL,'1',NULL,'1');
insert into TB_DICT (BANK, APPLICATION, GROUP_CODE, GROUP_NAME, META_VAL, META_NAME, CREATOR, CREATE_TIME, MOD_USER, MOD_DATE, ENABLE, REMARK, MOD_ABLE) VALUES ('0000','RPT','8422','疑似涉罪类型','0601','涉嫌非国家工作人员商业贿赂的可疑交易行为',NULL,NULL,NULL,NULL,'1',NULL,'1');

insert into TB_DICT (BANK, APPLICATION, GROUP_CODE, GROUP_NAME, META_VAL, META_NAME, CREATOR, CREATE_TIME, MOD_USER, MOD_DATE, ENABLE, REMARK, MOD_ABLE) VALUES ('0000','RPT','8422','疑似涉罪类型','0602','涉嫌非法关联经营的可疑交易行为',NULL,NULL,NULL,NULL,'1',NULL,'1');
insert into TB_DICT (BANK, APPLICATION, GROUP_CODE, GROUP_NAME, META_VAL, META_NAME, CREATOR, CREATE_TIME, MOD_USER, MOD_DATE, ENABLE, REMARK, MOD_ABLE) VALUES ('0000','RPT','8422','疑似涉罪类型','0603','涉嫌组织或参与经营非法金融机构的可疑交易行为',NULL,NULL,NULL,NULL,'1',NULL,'1');
insert into TB_DICT (BANK, APPLICATION, GROUP_CODE, GROUP_NAME, META_VAL, META_NAME, CREATOR, CREATE_TIME, MOD_USER, MOD_DATE, ENABLE, REMARK, MOD_ABLE) VALUES ('0000','RPT','8422','疑似涉罪类型','0604','涉嫌高利转贷的可疑交易行为',NULL,NULL,NULL,NULL,'1',NULL,'1');
insert into TB_DICT (BANK, APPLICATION, GROUP_CODE, GROUP_NAME, META_VAL, META_NAME, CREATOR, CREATE_TIME, MOD_USER, MOD_DATE, ENABLE, REMARK, MOD_ABLE) VALUES ('0000','RPT','8422','疑似涉罪类型','0605','涉嫌非法套取金融机构资金的可疑交易行为',NULL,NULL,NULL,NULL,'1',NULL,'1');
insert into TB_DICT (BANK, APPLICATION, GROUP_CODE, GROUP_NAME, META_VAL, META_NAME, CREATOR, CREATE_TIME, MOD_USER, MOD_DATE, ENABLE, REMARK, MOD_ABLE) VALUES ('0000','RPT','8422','疑似涉罪类型','0606','涉嫌非法吸收公众存款的可疑交易行为',NULL,NULL,NULL,NULL,'1',NULL,'1');
insert into TB_DICT (BANK, APPLICATION, GROUP_CODE, GROUP_NAME, META_VAL, META_NAME, CREATOR, CREATE_TIME, MOD_USER, MOD_DATE, ENABLE, REMARK, MOD_ABLE) VALUES ('0000','RPT','8422','疑似涉罪类型','0607','涉嫌擅自发行股票、公司、企业债券的可疑交易行为',NULL,NULL,NULL,NULL,'1',NULL,'1');
insert into TB_DICT (BANK, APPLICATION, GROUP_CODE, GROUP_NAME, META_VAL, META_NAME, CREATOR, CREATE_TIME, MOD_USER, MOD_DATE, ENABLE, REMARK, MOD_ABLE) VALUES ('0000','RPT','8422','疑似涉罪类型','0608','涉嫌内幕交易、操纵股价等证券类洗钱行为的可疑交易行为',NULL,NULL,NULL,NULL,'1',NULL,'1');

insert into TB_DICT (BANK, APPLICATION, GROUP_CODE, GROUP_NAME, META_VAL, META_NAME, CREATOR, CREATE_TIME, MOD_USER, MOD_DATE, ENABLE, REMARK, MOD_ABLE) VALUES ('0000','RPT','8422','疑似涉罪类型','0609','涉嫌非法挪用、拆借资金的可疑交易行为',NULL,NULL,NULL,NULL,'1',NULL,'1');
insert into TB_DICT (BANK, APPLICATION, GROUP_CODE, GROUP_NAME, META_VAL, META_NAME, CREATOR, CREATE_TIME, MOD_USER, MOD_DATE, ENABLE, REMARK, MOD_ABLE) VALUES ('0000','RPT','8422','疑似涉罪类型','0610','涉嫌非法跨境转移资金（例如逃汇）的可疑交易行为',NULL,NULL,NULL,NULL,'1',NULL,'1');
insert into TB_DICT (BANK, APPLICATION, GROUP_CODE, GROUP_NAME, META_VAL, META_NAME, CREATOR, CREATE_TIME, MOD_USER, MOD_DATE, ENABLE, REMARK, MOD_ABLE) VALUES ('0000','RPT','8422','疑似涉罪类型','0701','涉嫌集资诈骗的可疑交易行为',NULL,NULL,NULL,NULL,'1',NULL,'1');
insert into TB_DICT (BANK, APPLICATION, GROUP_CODE, GROUP_NAME, META_VAL, META_NAME, CREATOR, CREATE_TIME, MOD_USER, MOD_DATE, ENABLE, REMARK, MOD_ABLE) VALUES ('0000','RPT','8422','疑似涉罪类型','0702','涉嫌骗贷、信用证诈骗、票券诈骗等银行诈骗的可疑交易行为',NULL,NULL,NULL,NULL,'1',NULL,'1');
insert into TB_DICT (BANK, APPLICATION, GROUP_CODE, GROUP_NAME, META_VAL, META_NAME, CREATOR, CREATE_TIME, MOD_USER, MOD_DATE, ENABLE, REMARK, MOD_ABLE) VALUES ('0000','RPT','8422','疑似涉罪类型','0703','涉嫌有价证券诈骗的可疑交易行为',NULL,NULL,NULL,NULL,'1',NULL,'1');
insert into TB_DICT (BANK, APPLICATION, GROUP_CODE, GROUP_NAME, META_VAL, META_NAME, CREATOR, CREATE_TIME, MOD_USER, MOD_DATE, ENABLE, REMARK, MOD_ABLE) VALUES ('0000','RPT','8422','疑似涉罪类型','0704','涉嫌信用卡诈骗的可疑交易行为',NULL,NULL,NULL,NULL,'1',NULL,'1');
insert into TB_DICT (BANK, APPLICATION, GROUP_CODE, GROUP_NAME, META_VAL, META_NAME, CREATOR, CREATE_TIME, MOD_USER, MOD_DATE, ENABLE, REMARK, MOD_ABLE) VALUES ('0000','RPT','8422','疑似涉罪类型','0705','涉嫌保险诈骗的可疑交易行为',NULL,NULL,NULL,NULL,'1',NULL,'1');

insert into TB_DICT (BANK, APPLICATION, GROUP_CODE, GROUP_NAME, META_VAL, META_NAME, CREATOR, CREATE_TIME, MOD_USER, MOD_DATE, ENABLE, REMARK, MOD_ABLE) VALUES ('0000','RPT','8422','疑似涉罪类型','0801','涉嫌明知有七类洗钱上游犯罪的掩饰、隐瞒犯罪所得、犯罪收益的可疑交易行为',NULL,NULL,NULL,NULL,'1',NULL,'1');
insert into TB_DICT (BANK, APPLICATION, GROUP_CODE, GROUP_NAME, META_VAL, META_NAME, CREATOR, CREATE_TIME, MOD_USER, MOD_DATE, ENABLE, REMARK, MOD_ABLE) VALUES ('0000','RPT','8422','疑似涉罪类型','0802','涉嫌明知有其他上游犯罪的掩饰、隐瞒犯罪所得、犯罪收益的可疑交易行为',NULL,NULL,NULL,NULL,'1',NULL,'1');
insert into TB_DICT (BANK, APPLICATION, GROUP_CODE, GROUP_NAME, META_VAL, META_NAME, CREATOR, CREATE_TIME, MOD_USER, MOD_DATE, ENABLE, REMARK, MOD_ABLE) VALUES ('0000','RPT','8422','疑似涉罪类型','0901','涉嫌虚假注、验资的可疑交易行为',NULL,NULL,NULL,NULL,'1',NULL,'1');
insert into TB_DICT (BANK, APPLICATION, GROUP_CODE, GROUP_NAME, META_VAL, META_NAME, CREATOR, CREATE_TIME, MOD_USER, MOD_DATE, ENABLE, REMARK, MOD_ABLE) VALUES ('0000','RPT','8422','疑似涉罪类型','0902','涉嫌虚假出资、抽逃出资的可疑交易行为',NULL,NULL,NULL,NULL,'1',NULL,'1');
insert into TB_DICT (BANK, APPLICATION, GROUP_CODE, GROUP_NAME, META_VAL, META_NAME, CREATOR, CREATE_TIME, MOD_USER, MOD_DATE, ENABLE, REMARK, MOD_ABLE) VALUES ('0000','RPT','8422','疑似涉罪类型','0903','涉嫌欺诈发行股票、债券的可疑交易行为',NULL,NULL,NULL,NULL,'1',NULL,'1');
insert into TB_DICT (BANK, APPLICATION, GROUP_CODE, GROUP_NAME, META_VAL, META_NAME, CREATOR, CREATE_TIME, MOD_USER, MOD_DATE, ENABLE, REMARK, MOD_ABLE) VALUES ('0000','RPT','8422','疑似涉罪类型','1001','涉嫌逃税、避税、骗税等的可疑交易行为',NULL,NULL,NULL,NULL,'1',NULL,'1');
insert into TB_DICT (BANK, APPLICATION, GROUP_CODE, GROUP_NAME, META_VAL, META_NAME, CREATOR, CREATE_TIME, MOD_USER, MOD_DATE, ENABLE, REMARK, MOD_ABLE) VALUES ('0000','RPT','8422','疑似涉罪类型','1101','涉嫌组织、领导传销活动的可疑交易行为',NULL,NULL,NULL,NULL,'1',NULL,'1');

insert into TB_DICT (BANK, APPLICATION, GROUP_CODE, GROUP_NAME, META_VAL, META_NAME, CREATOR, CREATE_TIME, MOD_USER, MOD_DATE, ENABLE, REMARK, MOD_ABLE) VALUES ('0000','RPT','8422','疑似涉罪类型','1102','涉嫌非法经营(例如地下钱庄、非法买卖外汇、POS 机套现及其他套现等）的可疑交易行为',NULL,NULL,NULL,NULL,'1',NULL,'1');
insert into TB_DICT (BANK, APPLICATION, GROUP_CODE, GROUP_NAME, META_VAL, META_NAME, CREATOR, CREATE_TIME, MOD_USER, MOD_DATE, ENABLE, REMARK, MOD_ABLE) VALUES ('0000','RPT','8422','疑似涉罪类型','1201','涉嫌诈骗(例如电信诈骗)的可疑交易行为',NULL,NULL,NULL,NULL,'1',NULL,'1');
insert into TB_DICT (BANK, APPLICATION, GROUP_CODE, GROUP_NAME, META_VAL, META_NAME, CREATOR, CREATE_TIME, MOD_USER, MOD_DATE, ENABLE, REMARK, MOD_ABLE) VALUES ('0000','RPT','8422','疑似涉罪类型','1202','涉嫌职务侵占的可疑交易行为',NULL,NULL,NULL,NULL,'1',NULL,'1');
insert into TB_DICT (BANK, APPLICATION, GROUP_CODE, GROUP_NAME, META_VAL, META_NAME, CREATOR, CREATE_TIME, MOD_USER, MOD_DATE, ENABLE, REMARK, MOD_ABLE) VALUES ('0000','RPT','8422','疑似涉罪类型','1203','涉嫌挪用资金、物资的可疑交易行为',NULL,NULL,NULL,NULL,'1',NULL,'1');
insert into TB_DICT (BANK, APPLICATION, GROUP_CODE, GROUP_NAME, META_VAL, META_NAME, CREATOR, CREATE_TIME, MOD_USER, MOD_DATE, ENABLE, REMARK, MOD_ABLE) VALUES ('0000','RPT','8422','疑似涉罪类型','1301','涉嫌伪造、变造、买卖国家机关公文、证件、印章（例如骗购外汇）的可疑交易行为',NULL,NULL,NULL,NULL,'1',NULL,'1');
insert into TB_DICT (BANK, APPLICATION, GROUP_CODE, GROUP_NAME, META_VAL, META_NAME, CREATOR, CREATE_TIME, MOD_USER, MOD_DATE, ENABLE, REMARK, MOD_ABLE) VALUES ('0000','RPT','8422','疑似涉罪类型','1302','涉嫌组织经营赌博或为其转移资金的可疑交易行为',NULL,NULL,NULL,NULL,'1',NULL,'1');
insert into TB_DICT (BANK, APPLICATION, GROUP_CODE, GROUP_NAME, META_VAL, META_NAME, CREATOR, CREATE_TIME, MOD_USER, MOD_DATE, ENABLE, REMARK, MOD_ABLE) VALUES ('0000','RPT','8422','疑似涉罪类型','1401','司法机构或行政调查已介入的可疑交易行为',NULL,NULL,NULL,NULL,'1',NULL,'1');
insert into TB_DICT (BANK, APPLICATION, GROUP_CODE, GROUP_NAME, META_VAL, META_NAME, CREATOR, CREATE_TIME, MOD_USER, MOD_DATE, ENABLE, REMARK, MOD_ABLE) VALUES ('0000','RPT','8422','疑似涉罪类型','1402','涉嫌其他犯罪的可疑交易行为',NULL,NULL,NULL,NULL,'1',NULL,'1');

-- 11、银行卡类型
-- 新增银行卡类型基础数据：
-- 10：借记卡； 
-- 20：贷记卡； 
-- 30：准贷记卡； 
-- 90：其他
insert into TB_DICT (BANK, APPLICATION, GROUP_CODE, GROUP_NAME, META_VAL, META_NAME, CREATOR, CREATE_TIME, MOD_USER, MOD_DATE, ENABLE, REMARK, MOD_ABLE) VALUES ('0000','RPT','8423','银行卡类型','10','借记卡',NULL,NULL,NULL,NULL,'1',NULL,'1');
insert into TB_DICT (BANK, APPLICATION, GROUP_CODE, GROUP_NAME, META_VAL, META_NAME, CREATOR, CREATE_TIME, MOD_USER, MOD_DATE, ENABLE, REMARK, MOD_ABLE) VALUES ('0000','RPT','8423','银行卡类型','20','贷记卡',NULL,NULL,NULL,NULL,'1',NULL,'1');
insert into TB_DICT (BANK, APPLICATION, GROUP_CODE, GROUP_NAME, META_VAL, META_NAME, CREATOR, CREATE_TIME, MOD_USER, MOD_DATE, ENABLE, REMARK, MOD_ABLE) VALUES ('0000','RPT','8423','银行卡类型','30','准贷记卡',NULL,NULL,NULL,NULL,'1',NULL,'1');
insert into TB_DICT (BANK, APPLICATION, GROUP_CODE, GROUP_NAME, META_VAL, META_NAME, CREATOR, CREATE_TIME, MOD_USER, MOD_DATE, ENABLE, REMARK, MOD_ABLE) VALUES ('0000','RPT','8423','银行卡类型','90','其他',NULL,NULL,NULL,NULL,'1',NULL,'1');

-- 12、可疑报告紧急程度
-- 新增可疑报告紧急程度基础数据。

insert into TB_DICT (BANK, APPLICATION, GROUP_CODE, GROUP_NAME, META_VAL, META_NAME, CREATOR, CREATE_TIME, MOD_USER, MOD_DATE, ENABLE, REMARK, MOD_ABLE) VALUES ('0000','RPT','8424','可疑交易报告紧急程度','01','非特别紧急',NULL,NULL,NULL,NULL,'1',NULL,'1');
insert into TB_DICT (BANK, APPLICATION, GROUP_CODE, GROUP_NAME, META_VAL, META_NAME, CREATOR, CREATE_TIME, MOD_USER, MOD_DATE, ENABLE, REMARK, MOD_ABLE) VALUES ('0000','RPT','8424','可疑交易报告紧急程度','02','特别紧急',NULL,NULL,NULL,NULL,'1',NULL,'1');

-- 13、报送方向
-- 新增报送方向基础数据。
insert into TB_DICT (BANK, APPLICATION, GROUP_CODE, GROUP_NAME, META_VAL, META_NAME, CREATOR, CREATE_TIME, MOD_USER, MOD_DATE, ENABLE, REMARK, MOD_ABLE) VALUES ('0000','RPT','8425','报送方向','01','报告中国反洗钱监测分析中心',NULL,NULL,NULL,NULL,'1',NULL,'1');
insert into TB_DICT (BANK, APPLICATION, GROUP_CODE, GROUP_NAME, META_VAL, META_NAME, CREATOR, CREATE_TIME, MOD_USER, MOD_DATE, ENABLE, REMARK, MOD_ABLE) VALUES ('0000','RPT','8425','报送方向','02','报告中国反洗钱监测分析中心和人民银行当地分支机构',NULL,NULL,NULL,NULL,'1',NULL,'1');
insert into TB_DICT (BANK, APPLICATION, GROUP_CODE, GROUP_NAME, META_VAL, META_NAME, CREATOR, CREATE_TIME, MOD_USER, MOD_DATE, ENABLE, REMARK, MOD_ABLE) VALUES ('0000','RPT','8425','报送方向','03','报告中国反洗钱监测分析中心和当地公安机关',NULL,NULL,NULL,NULL,'1',NULL,'1');
insert into TB_DICT (BANK, APPLICATION, GROUP_CODE, GROUP_NAME, META_VAL, META_NAME, CREATOR, CREATE_TIME, MOD_USER, MOD_DATE, ENABLE, REMARK, MOD_ABLE) VALUES ('0000','RPT','8425','报送方向','04','报告中国反洗钱监测分析中心、人民银行当地分支机构和当地公安机关',NULL,NULL,NULL,NULL,'1',NULL,'1');
insert into TB_DICT (BANK, APPLICATION, GROUP_CODE, GROUP_NAME, META_VAL, META_NAME, CREATOR, CREATE_TIME, MOD_USER, MOD_DATE, ENABLE, REMARK, MOD_ABLE) VALUES ('0000','RPT','8425','报送方向','99','报告中国反洗钱监测分析中心和其他机构（若选择此项，报告机构应在字段“其他报送方向(ODRP)”对“其他机构”做进一步说明）。',NULL,NULL,NULL,NULL,'1',NULL,'1');

-- 14、非柜台交易方式
-- 新增非柜台交易方式基础数据
insert into TB_DICT (BANK, APPLICATION, GROUP_CODE, GROUP_NAME, META_VAL, META_NAME, CREATOR, CREATE_TIME, MOD_USER, MOD_DATE, ENABLE, REMARK, MOD_ABLE) VALUES ('0000','RPT','8426','非柜台交易方式','11','网上交易',NULL,NULL,NULL,NULL,'1',NULL,'1');
insert into TB_DICT (BANK, APPLICATION, GROUP_CODE, GROUP_NAME, META_VAL, META_NAME, CREATOR, CREATE_TIME, MOD_USER, MOD_DATE, ENABLE, REMARK, MOD_ABLE) VALUES ('0000','RPT','8426','非柜台交易方式','12','通过POS机交易',NULL,NULL,NULL,NULL,'1',NULL,'1');
insert into TB_DICT (BANK, APPLICATION, GROUP_CODE, GROUP_NAME, META_VAL, META_NAME, CREATOR, CREATE_TIME, MOD_USER, MOD_DATE, ENABLE, REMARK, MOD_ABLE) VALUES ('0000','RPT','8426','非柜台交易方式','13','通过电话交易',NULL,NULL,NULL,NULL,'1',NULL,'1');
insert into TB_DICT (BANK, APPLICATION, GROUP_CODE, GROUP_NAME, META_VAL, META_NAME, CREATOR, CREATE_TIME, MOD_USER, MOD_DATE, ENABLE, REMARK, MOD_ABLE) VALUES ('0000','RPT','8426','非柜台交易方式','14','通过热键机交易',NULL,NULL,NULL,NULL,'1',NULL,'1');
insert into TB_DICT (BANK, APPLICATION, GROUP_CODE, GROUP_NAME, META_VAL, META_NAME, CREATOR, CREATE_TIME, MOD_USER, MOD_DATE, ENABLE, REMARK, MOD_ABLE) VALUES ('0000','RPT','8426','非柜台交易方式','15','通过ATM',NULL,NULL,NULL,NULL,'1',NULL,'1');
insert into TB_DICT (BANK, APPLICATION, GROUP_CODE, GROUP_NAME, META_VAL, META_NAME, CREATOR, CREATE_TIME, MOD_USER, MOD_DATE, ENABLE, REMARK, MOD_ABLE) VALUES ('0000','RPT','8426','非柜台交易方式','16','通过传真交易',NULL,NULL,NULL,NULL,'1',NULL,'1');
insert into TB_DICT (BANK, APPLICATION, GROUP_CODE, GROUP_NAME, META_VAL, META_NAME, CREATOR, CREATE_TIME, MOD_USER, MOD_DATE, ENABLE, REMARK, MOD_ABLE) VALUES ('0000','RPT','8426','非柜台交易方式','17','营业场所交易（仅针对证券期货业）',NULL,NULL,NULL,NULL,'1',NULL,'1');
insert into TB_DICT (BANK, APPLICATION, GROUP_CODE, GROUP_NAME, META_VAL, META_NAME, CREATOR, CREATE_TIME, MOD_USER, MOD_DATE, ENABLE, REMARK, MOD_ABLE) VALUES ('0000','RPT','8426','非柜台交易方式','99','其他（若选择此项，报告机构应在字段“其他非柜台交易方式(OOCT)”对其类型做进一步说明）。',NULL,NULL,NULL,NULL,'1',NULL,'1');

-- 15、可疑交易报告触发点
-- 新增可疑交易报告触发点基础数据。
insert into TB_DICT (BANK, APPLICATION, GROUP_CODE, GROUP_NAME, META_VAL, META_NAME, CREATOR, CREATE_TIME, MOD_USER, MOD_DATE, ENABLE, REMARK, MOD_ABLE) VALUES ('0000','RPT','8427','可疑交易报告触发点','01','模型筛选',NULL,NULL,NULL,NULL,'1',NULL,'1');
insert into TB_DICT (BANK, APPLICATION, GROUP_CODE, GROUP_NAME, META_VAL, META_NAME, CREATOR, CREATE_TIME, MOD_USER, MOD_DATE, ENABLE, REMARK, MOD_ABLE) VALUES ('0000','RPT','8427','可疑交易报告触发点','02','执法部门指令（公安、纪检、安全等部门的境内冻结、协查等）',NULL,NULL,NULL,NULL,'1',NULL,'1');
insert into TB_DICT (BANK, APPLICATION, GROUP_CODE, GROUP_NAME, META_VAL, META_NAME, CREATOR, CREATE_TIME, MOD_USER, MOD_DATE, ENABLE, REMARK, MOD_ABLE) VALUES ('0000','RPT','8427','可疑交易报告触发点','03','监管部门指令（如央行、证监会、交易所等部门的警示或协查等）',NULL,NULL,NULL,NULL,'1',NULL,'1');
insert into TB_DICT (BANK, APPLICATION, GROUP_CODE, GROUP_NAME, META_VAL, META_NAME, CREATOR, CREATE_TIME, MOD_USER, MOD_DATE, ENABLE, REMARK, MOD_ABLE) VALUES ('0000','RPT','8427','可疑交易报告触发点','04','金融机构内部案件（机构内部违规违法行为等）',NULL,NULL,NULL,NULL,'1',NULL,'1');
insert into TB_DICT (BANK, APPLICATION, GROUP_CODE, GROUP_NAME, META_VAL, META_NAME, CREATOR, CREATE_TIME, MOD_USER, MOD_DATE, ENABLE, REMARK, MOD_ABLE) VALUES ('0000','RPT','8427','可疑交易报告触发点','05','社会舆情',NULL,NULL,NULL,NULL,'1',NULL,'1');
insert into TB_DICT (BANK, APPLICATION, GROUP_CODE, GROUP_NAME, META_VAL, META_NAME, CREATOR, CREATE_TIME, MOD_USER, MOD_DATE, ENABLE, REMARK, MOD_ABLE) VALUES ('0000','RPT','8427','可疑交易报告触发点','06','金融机构从业人员发现的身份、行为等异常状况',NULL,NULL,NULL,NULL,'1',NULL,'1');
insert into TB_DICT (BANK, APPLICATION, GROUP_CODE, GROUP_NAME, META_VAL, META_NAME, CREATOR, CREATE_TIME, MOD_USER, MOD_DATE, ENABLE, REMARK, MOD_ABLE) VALUES ('0000','RPT','8427','可疑交易报告触发点','99','其他（若选择此项，报告机构应在字段“其他可疑交易报告触发点(OTPR)”对其触发点做进一步说明）。',NULL,NULL,NULL,NULL,'1',NULL,'1');




