<?xml version="1.0" encoding="utf©\8"?>
<CHTR>
	<RBIF>
		<RICD>${RBIF.RICD}</RICD>
		<TSTN>${RBIF.CTTN}</TSTN>
		<MIRS>${RBIF.MIRS}</MIRS>
	</RBIF>
	<TSDTs>
		<#list TSDTs as TSDT>
		<TSDT seqno="${TSDT.SEQNO}">
			<OCNM>${TSDT.OCNM}</OCNM>
			<OTDT>${TSDT.OTDT}</OTDT>
			<OTCD>${TSDT.OTCD}</OTCD>
			<OTIC>${TSDT.OTIC}</OTIC>
			<RINI>
				<FINC>${TSDT.FINC}</FINC>
				<RLFC>${TSDT.RLFC}</RLFC>
			</RINI>
			<ATIF>
				<CATP>${TSDT.CATP}</CATP>
				<CTAC>${TSDT.CTAC}</CTAC>
				<OATM>${TSDT.OATM}</OATM>
				<CBCT>${TSDT.CBCT}</CBCT>
				<OCBT>${TSDT.OCBT}</OCBT>
				<CBCN>${TSDT.CBCN}</CBCN>
			</ATIF>
			<TBIF>
				<TBNM>${TSDT.TBNM}</TBNM>
				<TBIT>${TSDT.TBIT}</TBIT>
				<OITP>${TSDT.OITP}</OITP>
				<TBID>${TSDT.TBID}</TBID>
				<TBNT>${TSDT.TBNT}</TBNT>
			</TBIF>
			<TSIF>
				<TSTM>${TSDT.TSTM}</TSTM>
				<TRCD>${TSDT.TRCD}</TRCD>
				<TICD>${TSDT.TICD}</TICD>
				<RPMT>${TSDT.RPMT}</RPMT>
				<RPMN>${TSDT.RPMN}</RPMN>
				<TSTP>${TSDT.TSTP}</TSTP>
				<OCTT>${TSDT.OCTT}</OCTT>
				<OOCT>${TSDT.OOCT}</OOCT>
				<OCEC>${TSDT.OCEC}</OCEC>
				<BPTC>${TSDT.BPTC}</BPTC>
				<TSCT>${TSDT.TSCT}</TSCT>
				<TSDR>${TSDT.TSDR}</TSDR>
				<CRPP>${TSDT.CRPP}</CRPP>
				<CRTP>${TSDT.CRTP}</CRTP>
				<CRAT>${TSDT.CRAT}</CRAT>
				<CRMB>${TSDT.CRMB}</CRMB>
				<CUSD>${TSDT.CUSD}</CUSD>
			</TSIF>
			<TCIF>
				<CFIN>${TSDT.CFIN}</CFIN>
				<CFCT>${TSDT.CFCT}</CFCT>
				<CFIC>${TSDT.CFIC}</CFIC>
				<CFRC>${TSDT.CFRC}</CFRC>
				<TCNM>${TSDT.TCNM}</TCNM>
				<TCIT>${TSDT.TCIT}</TCIT>
				<OITP>${TSDT.OITP}</OITP>
				<TCID>${TSDT.TCID}</TCID>
				<TCAT>${TSDT.TCAT}</TCAT>
				<TCAC>${TSDT.TCAC}</TCAC>
			</TCIF>
			<ROTFs>
				<#list CommonFilter.doFilter(TSDT, ROTFs, "P_SEQNO1=P_SEQNO1") as ROTF>
				<ROTF seqno="${ROTF.SEQNO!}">${ROTF.ROTF}</ROTF>
				<ROTF seqno="${ROTF.SEQNO!}">${ROTF.ROTF}</ROTF>
			</ROTFs>
		</TSDT>
		</#list>
	</TSDTs>
</CHTR>