<?xml version="1.0" encoding="utf‐8"?>
<CHTR>
	<RBIF>
		<RICD>报告机构编码</RICD>
		<TSTN>欲修改交易总数</TSTN>
		<MIRS>人工补正标识</MIRS>
	</RBIF>
	<TSDTs>
		<TSDT seqno＝”1”>
			<OCNM>原客户号</OCNM>
			<OTDT>原大额交易发生日期</OTDT>
			<OTCD>原大额交易特征代码</OTCD>
			<OTIC>原业务标识号</OTIC>
			<RINI>
				<FINC>金融机构网点代码</FINC>
				<RLFC>金融机构与客户的关系</RLFC>
			</RINI>
			<ATIF>
				<CATP>客户账户类型</CATP>
				<CTAC>客户账号</CTAC>
				<OATM>客户账户开立时间</OATM>
				<CBCT>客户银行卡类型</CBCT>
				<OCBT>客户银行卡其他类型</OCBT>
				<CBCN>客户银行卡号码</CBCN>
			</ATIF>
			<TBIF>
				<TBNM>交易代办人姓名</TBNM>
				<TBIT>交易代办人身份证件/证明文件类型</TBIT>
				<OITP>其他身份证件/证明文件类型</OITP>
				<TBID>交易代办人身份证件/证明文件号码</TBID>
				<TBNT>交易代办人国籍</TBNT>
			</TBIF>
			<TSIF>
				<TSTM>交易时间</TSTM>
				<TRCD>交易发生地</TRCD>
				<TICD>业务标识号</TICD>
				<RPMT>收付款方匹配号类型</RPMT>
				<RPMN>收付款方匹配号</RPMN>
				<TSTP>交易方式</TSTP>
				<OCTT>非柜台交易方式</OCTT>
				<OOCT>其他非柜台交易方式</OOCT>
				<OCEC>非柜台交易方式的设备代码</OCEC>
				<BPTC>银行与支付机构之间的业务交易编码</BPTC>
				<TSCT>涉外收支交易分类与代码</TSCT>
				<TSDR>资金收付标志</TSDR>
				<CRPP>资金用途</CRPP>
				<CRTP>交易币种</CRTP>
				<CRAT>交易金额</CRAT>
				<CRMB>交易金额（折人民币）</CRMB>
				<CUSD>交易金额（折美元）</CUSD>
			</TSIF>
			<TCIF>
				<CFIN>对方金融机构网点名称</CFIN>
				<CFCT>对方金融机构网点代码类型</CFCT>
				<CFIC>对方金融机构网点代码</CFIC>
				<CFRC>对方金融机构网点行政区划代码</CFRC>
				<TCNM>交易对手姓名/名称</TCNM>
				<TCIT>交易对手身份证件/证明文件类型</TCIT>
				<OITP>其他身份证件/证明文件类型</OITP>
				<TCID>交易对手身份证件/证明文件号码</TCID>
				<TCAT>交易对手账户类型</TCAT>
				<TCAC>交易对手账号</TCAC>
			</TCIF>
			<ROTFs>
				<ROTF seqno=”1”>交易信息备注1</ROTF>
				<ROTF seqno=”2”>交易信息备注2</ROTF>
			</ROTFs>
		</TSDT>
		.........
	</TSDTs>
</CHTR>