/*
Navicat Oracle Data Transfer
Oracle Client Version : 11.2.0.1.0

Source Server         : ACC
Source Server Version : 120100
Source Host           : 106.14.30.97:1521
Source Schema         : DATA_FOUNTAIN

Target Server Type    : ORACLE
Target Server Version : 120100
File Encoding         : 65001

Date: 2017-06-06 09:55:06
*/


-- ----------------------------
-- Table structure for ZZ_VEHINSURANCE
-- ----------------------------
DROP TABLE "DATA_FOUNTAIN"."ZZ_VEHINSURANCE";
CREATE TABLE "DATA_FOUNTAIN"."ZZ_VEHINSURANCE" (
"FLAG_VEHINSURANCE" VARCHAR2(1 BYTE) NULL ,
"SUCCESS" VARCHAR2(10 BYTE) NULL ,
"RESULT" VARCHAR2(10 BYTE) NULL ,
"BUSINESSSTATUS" VARCHAR2(1 BYTE) NULL ,
"STATUSMESSAGE" VARCHAR2(100 BYTE) NULL ,
"CARUSEDTYPE" VARCHAR2(100 BYTE) NULL ,
"LICENSENO" VARCHAR2(10 BYTE) NULL ,
"LICENSEOWNER" VARCHAR2(30 BYTE) NULL ,
"POSTEDNAME" VARCHAR2(30 BYTE) NULL ,
"INSUREDNAME" VARCHAR2(30 BYTE) NULL ,
"PURCHASEPRICE" VARCHAR2(10 BYTE) NULL ,
"IDTYPE" VARCHAR2(1 BYTE) NULL ,
"CREDENTISLASNUM" VARCHAR2(18 BYTE) NULL ,
"CITYCODE" VARCHAR2(3 BYTE) NULL ,
"ENGINENO" VARCHAR2(10 BYTE) NULL ,
"REGISTERDATE" VARCHAR2(21 BYTE) NULL ,
"CARVIN" VARCHAR2(20 BYTE) NULL ,
"FORCEEXPIREDATE" VARCHAR2(10 BYTE) NULL ,
"BUSINESSEXPIREDATE" VARCHAR2(10 BYTE) NULL ,
"NEXTFORCESTARTDATE" VARCHAR2(10 BYTE) NULL ,
"NEXTBUSINESSSTARTDATE" VARCHAR2(10 BYTE) NULL ,
"SEATCOUNT" VARCHAR2(10 BYTE) NULL ,
"INSUREDIDCARD" VARCHAR2(2 BYTE) NULL ,
"INSUREDIDTYPE" VARCHAR2(18 BYTE) NULL ,
"INSUREDMOBILE" VARCHAR2(18 BYTE) NULL ,
"HOLDERIDCARD" VARCHAR2(18 BYTE) NULL ,
"HOLDERIDTYPE" VARCHAR2(18 BYTE) NULL ,
"HOLDERMOBILE" VARCHAR2(20 BYTE) NULL ,
"RATEFACTOR1" VARCHAR2(10 BYTE) NULL ,
"RATEFACTOR2" VARCHAR2(10 BYTE) NULL ,
"RATEFACTOR3" VARCHAR2(10 BYTE) NULL ,
"RATEFACTOR4" VARCHAR2(10 BYTE) NULL ,
"FUELTYPE" VARCHAR2(2 BYTE) NULL ,
"PROOFTYPE" VARCHAR2(2 BYTE) NULL ,
"CLAUSETYPE" VARCHAR2(2 BYTE) NULL ,
"LICENSECOLOR" VARCHAR2(1 BYTE) NULL ,
"RUNREGION" VARCHAR2(1 BYTE) NULL ,
"ISPUBLIC" VARCHAR2(1 BYTE) NULL ,
"BIZNO" VARCHAR2(20 BYTE) NULL ,
"FORCENO" VARCHAR2(20 BYTE) NULL ,
"SOURCE" VARCHAR2(5 BYTE) NULL ,
"CHESUN" VARCHAR2(10 BYTE) NULL ,
"SANZHE" VARCHAR2(10 BYTE) NULL ,
"DAOQIANG" VARCHAR2(10 BYTE) NULL ,
"SIJI" VARCHAR2(10 BYTE) NULL ,
"CHENGKE" VARCHAR2(10 BYTE) NULL ,
"BOLI" VARCHAR2(10 BYTE) NULL ,
"HUAHEN" VARCHAR2(10 BYTE) NULL ,
"BUJIMIANCHESUN" VARCHAR2(10 BYTE) NULL ,
"BUJIMIANSANZHE" VARCHAR2(10 BYTE) NULL ,
"BUJIMIANDAOQIANG" VARCHAR2(10 BYTE) NULL ,
"SHESHUI" VARCHAR2(10 BYTE) NULL ,
"ZIRAN" VARCHAR2(10 BYTE) NULL ,
"BUJIMIANCHENGKE" VARCHAR2(10 BYTE) NULL ,
"BUJIMIANSIJI" VARCHAR2(10 BYTE) NULL ,
"BUJIMIANHUAHEN" VARCHAR2(10 BYTE) NULL ,
"BUJIMIANSHESHUI" VARCHAR2(10 BYTE) NULL ,
"BUJIMIANZIRAN" VARCHAR2(10 BYTE) NULL ,
"BUJIMIANJINGSHENSUNSHI" VARCHAR2(10 BYTE) NULL ,
"HCSANFANGTEYUE" VARCHAR2(10 BYTE) NULL ,
"HCJINGSHENSUNSHI" VARCHAR2(10 BYTE) NULL ,
"CRATETIME" VARCHAR2(10 BYTE) NULL ,
"UID" VARCHAR2(32 BYTE) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON COLUMN "DATA_FOUNTAIN"."ZZ_VEHINSURANCE"."FLAG_VEHINSURANCE" IS '产品计费标识 ';
COMMENT ON COLUMN "DATA_FOUNTAIN"."ZZ_VEHINSURANCE"."SUCCESS" IS '查询状态';
COMMENT ON COLUMN "DATA_FOUNTAIN"."ZZ_VEHINSURANCE"."RESULT" IS '查询响应码';
COMMENT ON COLUMN "DATA_FOUNTAIN"."ZZ_VEHINSURANCE"."BUSINESSSTATUS" IS '查询结果';
COMMENT ON COLUMN "DATA_FOUNTAIN"."ZZ_VEHINSURANCE"."STATUSMESSAGE" IS '查询结果描述';
COMMENT ON COLUMN "DATA_FOUNTAIN"."ZZ_VEHINSURANCE"."CARUSEDTYPE" IS '使用性质';
COMMENT ON COLUMN "DATA_FOUNTAIN"."ZZ_VEHINSURANCE"."LICENSENO" IS '车牌号';
COMMENT ON COLUMN "DATA_FOUNTAIN"."ZZ_VEHINSURANCE"."LICENSEOWNER" IS '车主姓名';
COMMENT ON COLUMN "DATA_FOUNTAIN"."ZZ_VEHINSURANCE"."POSTEDNAME" IS '投保人';
COMMENT ON COLUMN "DATA_FOUNTAIN"."ZZ_VEHINSURANCE"."INSUREDNAME" IS '被保险人';
COMMENT ON COLUMN "DATA_FOUNTAIN"."ZZ_VEHINSURANCE"."PURCHASEPRICE" IS '新车购置价格';
COMMENT ON COLUMN "DATA_FOUNTAIN"."ZZ_VEHINSURANCE"."IDTYPE" IS '证件类型';
COMMENT ON COLUMN "DATA_FOUNTAIN"."ZZ_VEHINSURANCE"."CREDENTISLASNUM" IS '车主证件号码';
COMMENT ON COLUMN "DATA_FOUNTAIN"."ZZ_VEHINSURANCE"."CITYCODE" IS '城市ID';
COMMENT ON COLUMN "DATA_FOUNTAIN"."ZZ_VEHINSURANCE"."ENGINENO" IS '发动机号';
COMMENT ON COLUMN "DATA_FOUNTAIN"."ZZ_VEHINSURANCE"."REGISTERDATE" IS '车辆注册日期';
COMMENT ON COLUMN "DATA_FOUNTAIN"."ZZ_VEHINSURANCE"."CARVIN" IS '车辆识别代号';
COMMENT ON COLUMN "DATA_FOUNTAIN"."ZZ_VEHINSURANCE"."FORCEEXPIREDATE" IS '交强险到期时间';
COMMENT ON COLUMN "DATA_FOUNTAIN"."ZZ_VEHINSURANCE"."BUSINESSEXPIREDATE" IS '商业险到期时间';
COMMENT ON COLUMN "DATA_FOUNTAIN"."ZZ_VEHINSURANCE"."NEXTFORCESTARTDATE" IS '下年的交强起保日期';
COMMENT ON COLUMN "DATA_FOUNTAIN"."ZZ_VEHINSURANCE"."NEXTBUSINESSSTARTDATE" IS '下年的商业险起保日期';
COMMENT ON COLUMN "DATA_FOUNTAIN"."ZZ_VEHINSURANCE"."SEATCOUNT" IS '座位数量';
COMMENT ON COLUMN "DATA_FOUNTAIN"."ZZ_VEHINSURANCE"."INSUREDIDCARD" IS '被保人证件号';
COMMENT ON COLUMN "DATA_FOUNTAIN"."ZZ_VEHINSURANCE"."INSUREDIDTYPE" IS '被保人证件类型';
COMMENT ON COLUMN "DATA_FOUNTAIN"."ZZ_VEHINSURANCE"."INSUREDMOBILE" IS '被保人手机号';
COMMENT ON COLUMN "DATA_FOUNTAIN"."ZZ_VEHINSURANCE"."HOLDERIDCARD" IS '投保人证件号';
COMMENT ON COLUMN "DATA_FOUNTAIN"."ZZ_VEHINSURANCE"."HOLDERIDTYPE" IS '投保人证件类型';
COMMENT ON COLUMN "DATA_FOUNTAIN"."ZZ_VEHINSURANCE"."HOLDERMOBILE" IS '投保人联系方式';
COMMENT ON COLUMN "DATA_FOUNTAIN"."ZZ_VEHINSURANCE"."RATEFACTOR1" IS '无赔款系数';
COMMENT ON COLUMN "DATA_FOUNTAIN"."ZZ_VEHINSURANCE"."RATEFACTOR2" IS '自主渠道系数';
COMMENT ON COLUMN "DATA_FOUNTAIN"."ZZ_VEHINSURANCE"."RATEFACTOR3" IS '自主核保系数';
COMMENT ON COLUMN "DATA_FOUNTAIN"."ZZ_VEHINSURANCE"."RATEFACTOR4" IS '交通违法浮动系数';
COMMENT ON COLUMN "DATA_FOUNTAIN"."ZZ_VEHINSURANCE"."FUELTYPE" IS '燃料种类';
COMMENT ON COLUMN "DATA_FOUNTAIN"."ZZ_VEHINSURANCE"."PROOFTYPE" IS '条款种类';
COMMENT ON COLUMN "DATA_FOUNTAIN"."ZZ_VEHINSURANCE"."CLAUSETYPE" IS '条款类型';
COMMENT ON COLUMN "DATA_FOUNTAIN"."ZZ_VEHINSURANCE"."LICENSECOLOR" IS '号牌底色';
COMMENT ON COLUMN "DATA_FOUNTAIN"."ZZ_VEHINSURANCE"."RUNREGION" IS '行驶区域';
COMMENT ON COLUMN "DATA_FOUNTAIN"."ZZ_VEHINSURANCE"."ISPUBLIC" IS '车辆属性';
COMMENT ON COLUMN "DATA_FOUNTAIN"."ZZ_VEHINSURANCE"."BIZNO" IS '商业险保单号';
COMMENT ON COLUMN "DATA_FOUNTAIN"."ZZ_VEHINSURANCE"."FORCENO" IS '交强险保单号';
COMMENT ON COLUMN "DATA_FOUNTAIN"."ZZ_VEHINSURANCE"."SOURCE" IS '保险公司';
COMMENT ON COLUMN "DATA_FOUNTAIN"."ZZ_VEHINSURANCE"."CHESUN" IS '车损保额';
COMMENT ON COLUMN "DATA_FOUNTAIN"."ZZ_VEHINSURANCE"."SANZHE" IS '第三方责任险保额';
COMMENT ON COLUMN "DATA_FOUNTAIN"."ZZ_VEHINSURANCE"."DAOQIANG" IS '全车盗抢保险保额';
COMMENT ON COLUMN "DATA_FOUNTAIN"."ZZ_VEHINSURANCE"."SIJI" IS '车上人员责任险（司机）保额';
COMMENT ON COLUMN "DATA_FOUNTAIN"."ZZ_VEHINSURANCE"."CHENGKE" IS '车上人员责任险（乘客）保额';
COMMENT ON COLUMN "DATA_FOUNTAIN"."ZZ_VEHINSURANCE"."BOLI" IS '璃单独破碎险保额';
COMMENT ON COLUMN "DATA_FOUNTAIN"."ZZ_VEHINSURANCE"."HUAHEN" IS '车身划痕损失险保额';
COMMENT ON COLUMN "DATA_FOUNTAIN"."ZZ_VEHINSURANCE"."BUJIMIANCHESUN" IS '不计免赔险（车损）保额';
COMMENT ON COLUMN "DATA_FOUNTAIN"."ZZ_VEHINSURANCE"."BUJIMIANSANZHE" IS '不计免赔险（三者）保额';
COMMENT ON COLUMN "DATA_FOUNTAIN"."ZZ_VEHINSURANCE"."BUJIMIANDAOQIANG" IS '不计免赔险（盗抢）保额';
COMMENT ON COLUMN "DATA_FOUNTAIN"."ZZ_VEHINSURANCE"."SHESHUI" IS '涉水行驶损失险保额';
COMMENT ON COLUMN "DATA_FOUNTAIN"."ZZ_VEHINSURANCE"."ZIRAN" IS '自燃损失险保额';
COMMENT ON COLUMN "DATA_FOUNTAIN"."ZZ_VEHINSURANCE"."BUJIMIANCHENGKE" IS '不计免乘客保额';
COMMENT ON COLUMN "DATA_FOUNTAIN"."ZZ_VEHINSURANCE"."BUJIMIANSIJI" IS '不计免司机保额';
COMMENT ON COLUMN "DATA_FOUNTAIN"."ZZ_VEHINSURANCE"."BUJIMIANHUAHEN" IS '不计免划痕保额';
COMMENT ON COLUMN "DATA_FOUNTAIN"."ZZ_VEHINSURANCE"."BUJIMIANSHESHUI" IS '不计免涉水保额';
COMMENT ON COLUMN "DATA_FOUNTAIN"."ZZ_VEHINSURANCE"."BUJIMIANZIRAN" IS '不计免自燃保额';
COMMENT ON COLUMN "DATA_FOUNTAIN"."ZZ_VEHINSURANCE"."BUJIMIANJINGSHENSUNSHI" IS '不计免精神损失保额';
COMMENT ON COLUMN "DATA_FOUNTAIN"."ZZ_VEHINSURANCE"."HCSANFANGTEYUE" IS '机动车无法找到三方特约险保额';
COMMENT ON COLUMN "DATA_FOUNTAIN"."ZZ_VEHINSURANCE"."HCJINGSHENSUNSHI" IS '精神损失险保额';
COMMENT ON COLUMN "DATA_FOUNTAIN"."ZZ_VEHINSURANCE"."CRATETIME" IS '返回时间';
COMMENT ON COLUMN "DATA_FOUNTAIN"."ZZ_VEHINSURANCE"."UID" IS '32位主键';

-- ----------------------------
-- Indexes structure for table ZZ_VEHINSURANCE
-- ----------------------------

-- ----------------------------
-- Checks structure for table ZZ_VEHINSURANCE
-- ----------------------------
ALTER TABLE "DATA_FOUNTAIN"."ZZ_VEHINSURANCE" ADD CHECK ("UID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table ZZ_VEHINSURANCE
-- ----------------------------
ALTER TABLE "DATA_FOUNTAIN"."ZZ_VEHINSURANCE" ADD PRIMARY KEY ("UID");
